#!/bin/sh
set -eu
ziran=$1
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT HUP INT TERM
mkdir -p "$work/driver" "$work/registry"
cat > "$work/go.mod" <<'GO'
module fixture
go 1.24
GO
cat > "$work/registry/registry.go" <<'GO'
package registry
var Count int
GO
cat > "$work/driver/driver.go" <<'GO'
package driver
import "fixture/registry"
type Handle struct { Value int32 }
func init() { registry.Count++ }
func Answer() int32 { return 42 }
GO
cat > "$work/plain.zi" <<'ZI'
driver :: #system_library "go:fixture/driver";
#scope_file
InitializeRaw :: () #foreign driver "init";
#scope_export
Initialize :: () { InitializeRaw() }
ZI
cat > "$work/calls.zi" <<'ZI'
driver :: #system_library "go:fixture/driver";
InitializeRaw :: () #foreign driver "init";
AnswerRaw :: () -> s32 #foreign driver "Answer";
Read :: () -> s32 {
    InitializeRaw()
    return AnswerRaw()
}
ZI
cat > "$work/handles.zi" <<'ZI'
driver :: #system_library "go:fixture/driver";
Handle :: #type #foreign driver "Handle";
InitializeRaw :: () #foreign driver "init";
Initialize :: () { InitializeRaw() }
ZI
cat > "$work/app.zi" <<'ZI'
plain :: #import "plain";
calls :: #import "calls";
handles :: #import "handles";
Run :: () -> s32 {
    plain.Initialize()
    handles.Initialize()
    return calls.Read()
}
#program_export
Portable :: () -> s32 { return 42 }
VoidEntry :: () {}
ZI
"$ziran" ir --root "$work" -o "$work/ir" "$work/app.zi"
python3 - "$work/ir/plain.zir" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
data = path.read_bytes()
signature = b'InitializeRaw :: () #foreign driver "init";'
assert data.count(signature) == 1
path.write_bytes(data.replace(signature, b'?' * len(signature)))
PY
for form in source saved; do
    input=$work/app.zi
    if test "$form" = saved; then input=$work/ir/app.zir; fi
    out=$work/$form-go
    "$ziran" build --target=go --no-main --pkg main --root "$work" -o "$out" "$input"
    cat > "$out/main.go" <<'GO'
package main
import "fixture/registry"
var initializedBeforeGlobals = registry.Count == 1
func main() {
    if !initializedBeforeGlobals || registry.Count != 1 { panic("package startup order") }
    if App_Run() != 42 || App_Run() != 42 || registry.Count != 1 { panic("package initialized again") }
    if (Handle{Value: 42}).Value != 42 { panic("named type import lost") }
}
GO
    (cd "$out" && GOWORK=off GOFLAGS=-buildvcs=false GOCACHE=/tmp/ziran-package-init-cache go run -race .)
    (cd "$out" && GOWORK=off GOFLAGS=-buildvcs=false CGO_ENABLED=0 GOCACHE=/tmp/ziran-package-init-cache go run .)
    entry=$work/$form-entry
    "$ziran" build --target=go --exe --pkg main --root "$work" --entry app:Run -o "$entry" "$input"
    grep -q '^// Code generated by zi2go from app.zi.' "$entry/ziran_entry.go"
    (cd "$entry" && GOWORK=off GOFLAGS=-buildvcs=false GOCACHE=/tmp/ziran-package-init-cache go build -o "$work/$form-bin" .)
    result=0
    "$work/$form-bin" || result=$?
    test "$result" = 42
    "$ziran" build --target=go --exe --prune-stale --pkg main --root "$work" --entry app:VoidEntry -o "$entry" "$input"
    test -f "$entry/ziran_entry.go"
    "$ziran" build --target=go --no-main --prune-stale --pkg main --root "$work" -o "$entry" "$input"
    test ! -f "$entry/ziran_entry.go"
    "$ziran" bundle --root "$work" --entry app:Portable -o "$work/$form.zib" "$input"
    test "$("$ziran" run "$work/$form.zib")" = 42
    for target in c cpp; do
        if "$ziran" build --target="$target" --root "$work" --entry app:Run -o "$work/rejected" "$input" > "$work/rejected.log" 2>&1; then
            echo "reachable Go initialization accepted by $target" >&2
            exit 1
        fi
    done
    if "$ziran" bundle --root "$work" --entry app:Run -o "$work/rejected.zib" "$input" > "$work/rejected.log" 2>&1; then
        echo 'reachable Go initialization accepted by portable bundle' >&2
        exit 1
    fi
done
for file in plain.go calls.go handles.go app.go; do
    cmp "$work/source-go/$file" "$work/saved-go/$file"
done
for declaration in 'Initialize :: (value: s32)' 'Initialize :: () -> s32' \
    'Initialize :: () #go_defer' 'Initialize :: () #go_field' \
    'Initialize :: () #go_results' 'Initialize :: (values: []s32) #go_variadic'; do
    printf 'driver :: #system_library "go:fixture/driver";\n%s #foreign driver "init";\n' "$declaration" > "$work/bad.zi"
    if "$ziran" ir --root "$work" -o "$work/bad-ir" "$work/bad.zi" > "$work/bad.log" 2>&1; then
        echo "invalid package initialization accepted: $declaration" >&2
        exit 1
    fi
    grep -Eq 'Go package initialization|#go_field|#go_results' "$work/bad.log"
done
echo 'Go package initialization and generated entry ownership: passed'
