#!/bin/sh
set -eu

ziran=$1
tools=$(dirname "$ziran")
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT HUP INT TERM

# `ziran build -o DIR` owns DIR: generated files an earlier build left there
# (for example under a module name that has since changed) are removed so a
# `DIR/*.c` link cannot pick up dead copies. Other files are kept.
cat > "$work/app.zi" <<'ZI'
#program_export
Answer :: () -> s32 { return 42 }
ZI

check_target() {
    target=$1
    marker=$2
    extension=$3
    output="$work/$target"
    mkdir -p "$output"
    printf '%s old.zi. */\n' "$marker" > "$output/old.$extension"
    printf 'kept by the user\n' > "$output/notes.$extension"
    "$ziran" build --target="$target" --root "$work" -o "$output" \
        "$work/app.zi"
    if test -e "$output/old.$extension"; then
        echo "$target build kept a stale generated file" >&2
        exit 1
    fi
    test -f "$output/notes.$extension"
    test -f "$output/app.$extension"
}
check_target c '/* Generated by zi2c from' c
check_target cpp '/* Generated by zi2cpp from' cpp
check_target go '// Code generated by zi2go from' go

# Running a backend directly still accumulates, so several invocations can
# share one directory.
mkdir -p "$work/shared"
printf '/* Generated by zi2c from other.zi. */\n' > "$work/shared/other.c"
"$tools/zi2c" --no-main --root "$work" -o "$work/shared" "$work/app.zi"
test -f "$work/shared/other.c"
echo 'stale generated output: C, C++, Go pruned; direct backends accumulate'
