#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#if defined(__linux__)
#include <stdint.h>
#include <stdio.h>

/* Keep libc's const char * declarations out of generated byte-pointer C. */
int32_t
file_rename_at(int32_t old_directory, uint8_t *source,
               int32_t new_directory, uint8_t *destination)
{
    return renameat(old_directory, (const char *)source,
                    new_directory, (const char *)destination);
}

int32_t
file_rename_at2(int32_t old_directory, uint8_t *source,
                int32_t new_directory, uint8_t *destination, uint32_t flags)
{
    return renameat2(old_directory, (const char *)source,
                     new_directory, (const char *)destination, flags);
}
#endif
