/* Generated by zi2c from compiler_source.zi. */
#include "compiler_source.h"
static uint8_t compiler_source_Byte(String source, int64_t at);
static bool compiler_source_Space(uint8_t byte);
static bool compiler_source_Letter(uint8_t byte);
static int64_t compiler_source_SkipSpace(String source, int64_t at);
static bool compiler_source_Matches(String source, int64_t at, String text);
static int64_t compiler_source_Find(String source, String text);
static int64_t compiler_source_AfterQuote(String source, int64_t at);
static void compiler_source_Put(Slice output, int64_t* used, uint8_t byte);
static void compiler_source_PutScanned(Slice output, int64_t* used, uint8_t byte, int64_t* gaps);
static void compiler_source_PutRaw(Slice output, int64_t* used, uint8_t byte);

static uint8_t
compiler_source_Byte(String source, int64_t at)
{
    bool value_0 = at < 0LL;
    if (!value_0) {
        int64_t value_1 = (int64_t)(source).length;
        value_0 = (at >= value_1);
    }
    if (value_0) {
        return 0;
    }
    return (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
}

static bool
compiler_source_Space(uint8_t byte)
{
    return byte == 32 || (byte >= 9 && byte <= 13);
}

static bool
compiler_source_Letter(uint8_t byte)
{
    return (byte >= 65 && byte <= 90) || (byte >= 97 && byte <= 122) || byte == 95;
}

static int64_t
compiler_source_SkipSpace(String source, int64_t at)
{
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        bool value_1 = at < value_0;
        if (value_1) {
            bool value_2 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, at));
            value_1 = value_2;
        }
        if (!value_1) { break; }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return at;
}

static bool
compiler_source_Matches(String source, int64_t at, String text)
{
    bool value_0 = at >= 0LL;
    if (value_0) {
        int64_t value_1 = (int64_t)(source).length;
        value_0 = (at <= value_1);
    }
    bool value_2 = value_0;
    if (value_2) {
        int64_t value_3 = (int64_t)(text).length;
        int64_t value_4 = (int64_t)((uint64_t)((int64_t)(source).length) - (uint64_t)at);
        value_2 = (value_3 <= value_4);
    }
    bool value_5 = value_2;
    if (value_5) {
        String value_6 = source;
        String value_7 = StringRange(value_6, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)((int64_t)(text).length))));
        value_5 = (StringEqual(value_7, text));
    }
    return value_5;
}

static int64_t
compiler_source_Find(String source, String text)
{
    int64_t at = 0LL;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at <= value_0)) { break; }
        if (compiler_source_Matches(source, at, text)) {
            return at;
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return -1LL;
}

static int64_t
compiler_source_AfterQuote(String source, int64_t at)
{
    uint8_t quote = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
    at = (int64_t)((uint64_t)at + UINT64_C(1));
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        at = (int64_t)((uint64_t)at + UINT64_C(1));
        bool value_1 = byte == 92;
        if (value_1) {
            int64_t value_2 = (int64_t)(source).length;
            value_1 = (at < value_2);
        }
        if (value_1) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        } else if (byte == quote) {
            break;
        }
    }
    return at;
}

static void
compiler_source_Put(Slice output, int64_t* used, uint8_t byte)
{
    int64_t value_0 = *(used);
    int64_t value_1 = (int64_t)(output).length;
    if (value_0 < value_1) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)*(used))] = byte;
    }
    (*(used)) = (int64_t)((uint64_t)((*(used))) + UINT64_C(1));
}

static void
compiler_source_PutScanned(Slice output, int64_t* used, uint8_t byte, int64_t* gaps)
{
    compiler_source_Put(output, used, byte);
    if (byte == 10) {
        while (true) {
            int64_t value_0 = *(gaps);
            if (!(value_0 > 0LL)) { break; }
            compiler_source_Put(output, used, 10);
            (*(gaps)) = (int64_t)((uint64_t)((*(gaps))) - UINT64_C(1));
        }
    }
}

static void
compiler_source_PutRaw(Slice output, int64_t* used, uint8_t byte)
{
    uint8_t escaped = 0;
    if (byte == 34 || byte == 92) {
        escaped = byte;
    } else if (byte == 10) {
        escaped = 110;
    } else if (byte == 13) {
        escaped = 114;
    } else if (byte == 9) {
        escaped = 116;
    }
    if (escaped != 0) {
        compiler_source_Put(output, used, 92);
        compiler_source_Put(output, used, escaped);
    } else if (byte < 32 || byte == 127) {
        String digits = StringLiteral("0123456789abcdef");
        compiler_source_Put(output, used, 92);
        compiler_source_Put(output, used, 120);
        compiler_source_Put(output, used, (uint8_t)ZIRAN_INDEX(digits.data, digits.length, ((uint8_t)(byte >> 4))));
        compiler_source_Put(output, used, (uint8_t)ZIRAN_INDEX(digits.data, digits.length, ((uint8_t)((uint32_t)byte & 15u))));
    } else {
        compiler_source_Put(output, used, byte);
    }
}

bool
compiler_source_SourceIdentifier(uint8_t byte)
{
    bool value_0 = compiler_source_Letter(byte);
    return value_0 || (byte >= 48 && byte <= 57);
}

bool
compiler_source_StartsWord(String source, String word)
{
    bool value_0 = compiler_source_Matches(source, 0LL, word);
    if (!value_0) {
        return false;
    }
    uint8_t byte = compiler_source_Byte(source, (int64_t)(word).length);
    return byte == 0 || byte == 32 || byte == 9 || byte == 40 || byte == 34 || byte == 123;
}

bool
compiler_source_IdentifierText(String source, bool member_path)
{
    int64_t value_0 = (int64_t)(source).length;
    bool value_1 = value_0 == 0LL;
    if (!value_1) {
        bool value_2 = compiler_source_Letter((uint8_t)ZIRAN_INDEX(source.data, source.length, 0));
        value_1 = !value_2;
    }
    if (value_1) {
        return false;
    }
    int64_t at = 1LL;
    while (true) {
        int64_t value_3 = (int64_t)(source).length;
        if (!(at < value_3)) { break; }
        if (compiler_source_SourceIdentifier((uint8_t)ZIRAN_INDEX(source.data, source.length, at))) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        } else {
            bool value_4 = member_path && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 46;
            bool value_5 = value_4;
            if (value_5) {
                bool value_6 = compiler_source_Letter(compiler_source_Byte(source, (int64_t)((uint64_t)at + UINT64_C(1))));
                value_5 = value_6;
            }
            if (value_5) {
                at = (int64_t)((uint64_t)at + UINT64_C(2));
            } else {
                return false;
            }
        }
    }
    return true;
}

bool
compiler_source_NonJaiControl(String source, String word)
{
    bool value_0 = compiler_source_StartsWord(source, word);
    if (!value_0) {
        return false;
    }
    int64_t at = compiler_source_SkipSpace(source, (int64_t)(word).length);
    uint8_t byte = compiler_source_Byte(source, at);
    if (byte == 40) {
        String value_1 = source;
        int64_t value_2 = compiler_source_Find(StringRange(value_1, (int64_t)at, (int64_t)value_1.length), StringLiteral("{"));
        return value_2 >= 0LL;
    }
    String operators = StringLiteral(":=.[+-*/%&|^<>!");
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_3 = (int64_t)(operators).length;
            if (!(it_index < value_3)) { break; }
            uint8_t operator_byte = (uint8_t)ZIRAN_INDEX(operators.data, operators.length, it_index);
            if (byte == operator_byte) {
                return false;
            }
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
    bool value_4 = byte == 0 || byte == 59 || byte == 123;
    bool value_5 = value_4;
    if (!value_5) {
        bool value_6 = compiler_source_SourceIdentifier(byte);
        value_5 = value_6;
    }
    return value_5;
}

bool
compiler_source_LooksLikeLabel(String source)
{
    int64_t at = 0LL;
    while (compiler_source_SourceIdentifier(compiler_source_Byte(source, at))) {
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    bool value_0 = at == 0LL;
    bool value_1 = value_0;
    if (!value_1) {
        bool value_2 = compiler_source_Byte(source, at) != 58;
        value_1 = value_2;
    }
    if (value_1) {
        return false;
    }
    at = compiler_source_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)));
    int64_t value_3 = (int64_t)(source).length;
    bool value_4 = at == value_3;
    if (!value_4) {
        String value_5 = source;
        value_4 = (StringEqual(StringRange(value_5, (int64_t)at, (int64_t)value_5.length), StringLiteral(";")));
    }
    return value_4;
}

StatementKind
compiler_source_ClassifyStatement(String source)
{
    if (compiler_source_Byte(source, 0LL) == 125) {
        return StatementKind_BlockClose;
    }
    if (StringEqual(source, StringLiteral("{"))) {
        return StatementKind_BlockOpen;
    }
    bool value_0 = compiler_source_StartsWord(source, StringLiteral("if"));
    bool value_1 = value_0;
    if (!value_1) {
        bool value_2 = compiler_source_StartsWord(source, StringLiteral("else"));
        value_1 = value_2;
    }
    if (value_1) {
        return StatementKind_If;
    }
    if (compiler_source_StartsWord(source, StringLiteral("while"))) {
        return StatementKind_While;
    }
    if (compiler_source_StartsWord(source, StringLiteral("for"))) {
        return StatementKind_For;
    }
    bool value_3 = compiler_source_StartsWord(source, StringLiteral("case"));
    if (value_3 || StringEqual(source, StringLiteral("case;"))) {
        return StatementKind_Case;
    }
    bool value_4 = compiler_source_StartsWord(source, StringLiteral("return"));
    if (value_4 || StringEqual(source, StringLiteral("return;"))) {
        return StatementKind_Return;
    }
    bool value_5 = StringEqual(source, StringLiteral("unreachable")) || StringEqual(source, StringLiteral("unreachable;"));
    if (value_5) {
        return StatementKind_Unreachable;
    }
    bool value_6 = compiler_source_StartsWord(source, StringLiteral("break"));
    if (value_6 || StringEqual(source, StringLiteral("break;"))) {
        return StatementKind_Break;
    }
    bool value_7 = compiler_source_StartsWord(source, StringLiteral("continue"));
    if (value_7 || StringEqual(source, StringLiteral("continue;"))) {
        return StatementKind_Continue;
    }
    if (compiler_source_StartsWord(source, StringLiteral("defer"))) {
        return StatementKind_Defer;
    }
    if (compiler_source_StartsWord(source, StringLiteral("unused"))) {
        return StatementKind_Unused;
    }
    int64_t colon = compiler_source_Find(source, StringLiteral(": "));
    if (colon < 0LL) {
        colon = compiler_source_Find(source, StringLiteral(": ["));
    }
    bool value_8 = colon > 0LL;
    bool value_9 = value_8;
    if (value_9) {
        String value_10 = source;
        bool value_11 = compiler_source_IdentifierText(StringRange(value_10, (int64_t)0LL, (int64_t)colon), false);
        value_9 = value_11;
    }
    if (value_9) {
        return StatementKind_Declaration;
    }
    String rejected[11] = {StringLiteral("s8 "), StringLiteral("s16 "), StringLiteral("s32 "), StringLiteral("s64 "), StringLiteral("float32 "), StringLiteral("float64 "), StringLiteral("bool "), StringLiteral("unsigned "), StringLiteral("long "), StringLiteral("const "), StringLiteral("struct ")};
    for (int64_t it_index = 0LL; it_index < 11; it_index++) {
        String prefix = ZIRAN_INDEX(rejected, 11, it_index);
        if (compiler_source_Matches(source, 0LL, prefix)) {
            return StatementKind_Declaration;
        }
    }
    int64_t at = 0LL;
    int32_t depth = 0;
    while (true) {
        int64_t value_12 = (int64_t)(source).length;
        if (!(at < value_12)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 40 || byte == 91 || byte == 123) {
            depth = (int32_t)((uint32_t)depth + 1u);
        } else if (byte == 41 || byte == 93 || byte == 125) {
            if (depth > 0) {
                depth = (int32_t)((uint32_t)depth - 1u);
            }
        } else {
            bool value_13 = depth == 0;
            bool value_14 = value_13;
            if (value_14) {
                bool value_15 = compiler_source_Matches(source, at, StringLiteral(":="));
                value_14 = value_15;
            }
            if (value_14) {
                return StatementKind_Declaration;
            } else if (byte == 61 && depth == 0) {
                return StatementKind_Assignment;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    int64_t value_16 = compiler_source_Find(source, StringLiteral("("));
    bool value_17 = value_16 >= 0LL;
    if (!value_17) {
        int64_t value_18 = compiler_source_Find(source, StringLiteral("+"));
        value_17 = (value_18 >= 0LL);
    }
    bool value_19 = value_17;
    if (!value_19) {
        int64_t value_20 = compiler_source_Find(source, StringLiteral("-"));
        value_19 = (value_20 >= 0LL);
    }
    if (value_19) {
        return StatementKind_Expression;
    }
    return StatementKind_Unknown;
}

void
compiler_source_NormalizeRecordSeparators(Slice body, bool split_commas)
{
    int64_t at = 0LL;
    bool quoted = false;
    int32_t nesting = 0;
    while (true) {
        int64_t value_0 = (int64_t)(body).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = ((uint8_t *)body.data)[SliceIndex(body, (int64_t)at)];
        if (quoted) {
            bool value_1 = byte == 92;
            if (value_1) {
                int64_t value_2 = (int64_t)((uint64_t)at + UINT64_C(1));
                int64_t value_3 = (int64_t)(body).length;
                value_1 = (value_2 < value_3);
            }
            if (value_1) {
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            } else if (byte == 34) {
                quoted = false;
            }
        } else if (byte == 34) {
            quoted = true;
        } else if (byte == 91 || byte == 40) {
            nesting = (int32_t)((uint32_t)nesting + 1u);
        } else if (byte == 93 || byte == 41) {
            nesting = (int32_t)((uint32_t)nesting - 1u);
        } else if (nesting == 0 && (byte == 59 || (split_commas && byte == 44))) {
            ((uint8_t *)body.data)[SliceIndex(body, (int64_t)at)] = 10;
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
}

bool
compiler_source_ContainsDirective(String source, String directive)
{
    int64_t at = 0LL;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        if ((uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 34) {
            at = compiler_source_AfterQuote(source, at);
        } else if (compiler_source_Matches(source, at, StringLiteral("//"))) {
            return false;
        } else {
            bool value_1 = compiler_source_Matches(source, at, directive);
            bool value_2 = value_1;
            if (value_2) {
                bool value_3 = compiler_source_SourceIdentifier(compiler_source_Byte(source, (int64_t)((uint64_t)at + (uint64_t)((int64_t)(directive).length))));
                value_2 = !value_3;
            }
            if (value_2) {
                return true;
            } else {
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            }
        }
    }
    return false;
}

SourceRewrite
compiler_source_RewriteRawStrings(String source, Slice output, int64_t marker_limit)
{
    SourceRewrite result = {0};
    int64_t at = 0LL;
    int64_t used = 0LL;
    int64_t gaps = 0LL;
    int32_t line = 1;
    int32_t column = 1;
    uint8_t quote = 0;
    bool line_comment = false;
    int32_t comment_depth = 0;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        bool value_1 = !line_comment && quote == 0;
        bool value_2 = value_1;
        if (value_2) {
            bool value_3 = compiler_source_Matches(source, at, StringLiteral("/*"));
            bool value_4 = value_3;
            if (!value_4) {
                bool value_5 = comment_depth > 0;
                bool value_6 = value_5;
                if (value_6) {
                    bool value_7 = compiler_source_Matches(source, at, StringLiteral("*/"));
                    value_6 = value_7;
                }
                value_4 = value_6;
            }
            value_2 = value_4;
        }
        if (value_2) {
            if (byte == 47) {
                comment_depth = (int32_t)((uint32_t)comment_depth + 1u);
            } else {
                comment_depth = (int32_t)((uint32_t)comment_depth - 1u);
            }
            compiler_source_Put(output, &(used), byte);
            compiler_source_Put(output, &(used), (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at + UINT64_C(1)))));
            at = (int64_t)((uint64_t)at + UINT64_C(2));
            column = (int32_t)((uint32_t)column + 2u);
            continue;
        }
        if (!line_comment && comment_depth == 0 && quote == 0) {
            if (compiler_source_Matches(source, at, StringLiteral("//"))) {
                line_comment = true;
            } else if (byte == 34 || byte == 39) {
                quote = byte;
            } else {
                bool value_8 = compiler_source_Matches(source, at, StringLiteral("#string"));
                bool value_9 = value_8;
                if (value_9) {
                    bool value_10 = at == 0LL;
                    bool value_11 = value_10;
                    if (!value_11) {
                        bool value_12 = compiler_source_SourceIdentifier((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at - UINT64_C(1)))));
                        value_11 = !value_12;
                    }
                    value_9 = value_11;
                }
                bool value_13 = value_9;
                bool value_14 = value_13;
                if (value_14) {
                    int64_t value_15 = (int64_t)((uint64_t)at + UINT64_C(7));
                    int64_t value_16 = (int64_t)(source).length;
                    bool value_17 = value_15 == value_16;
                    bool value_18 = value_17;
                    if (!value_18) {
                        bool value_19 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at + UINT64_C(7)))));
                        value_18 = value_19;
                    }
                    value_14 = value_18;
                }
                if (value_14) {
                    result.line = line;
                    result.column = column;
                    int64_t cursor = (int64_t)((uint64_t)at + UINT64_C(7));
                    while (true) {
                        bool value_20 = compiler_source_Byte(source, cursor) == 32;
                        bool value_21 = value_20;
                        if (!value_21) {
                            bool value_22 = compiler_source_Byte(source, cursor) == 9;
                            value_21 = value_22;
                        }
                        if (!value_21) { break; }
                        cursor = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    }
                    int64_t begin = cursor;
                    while (compiler_source_SourceIdentifier(compiler_source_Byte(source, cursor))) {
                        cursor = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    }
                    int64_t end = cursor;
                    result.marker_begin = begin;
                    result.marker_end = end;
                    bool value_23 = end == begin;
                    if (!value_23) {
                        int64_t value_24 = (int64_t)((uint64_t)end - (uint64_t)begin);
                        value_23 = (value_24 >= marker_limit);
                    }
                    bool value_25 = value_23;
                    bool value_26 = value_25;
                    if (!value_26) {
                        bool value_27 = compiler_source_Letter(compiler_source_Byte(source, begin));
                        value_26 = !value_27;
                    }
                    if (value_26) {
                        result.error = SourceError_Delimiter;
                        return result;
                    }
                    while (true) {
                        bool value_28 = compiler_source_Byte(source, cursor) == 32;
                        bool value_29 = value_28;
                        if (!value_29) {
                            bool value_30 = compiler_source_Byte(source, cursor) == 9;
                            value_29 = value_30;
                        }
                        if (!value_29) { break; }
                        cursor = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    }
                    if (compiler_source_Byte(source, cursor) == 13) {
                        cursor = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    }
                    int64_t value_31 = (int64_t)(source).length;
                    if (cursor >= value_31 || (uint8_t)ZIRAN_INDEX(source.data, source.length, cursor) != 10) {
                        result.error = SourceError_DelimiterLine;
                        return result;
                    }
                    int64_t body = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    int64_t close = body;
                    String value_32 = source;
                    String marker = StringRange(value_32, (int64_t)begin, (int64_t)end);
                    while (true) {
                        int64_t value_33 = (int64_t)(source).length;
                        if (!(close < value_33)) { break; }
                        bool value_34 = compiler_source_Matches(source, close, marker);
                        bool value_35 = value_34;
                        if (value_35) {
                            bool value_36 = compiler_source_SourceIdentifier(compiler_source_Byte(source, (int64_t)((uint64_t)close + (uint64_t)((int64_t)(marker).length))));
                            value_35 = !value_36;
                        }
                        if (value_35) {
                            break;
                        }
                        while (true) {
                            int64_t value_37 = (int64_t)(source).length;
                            if (!(close < value_37 && (uint8_t)ZIRAN_INDEX(source.data, source.length, close) != 10)) { break; }
                            close = (int64_t)((uint64_t)close + UINT64_C(1));
                        }
                        int64_t value_38 = (int64_t)(source).length;
                        if (close < value_38) {
                            close = (int64_t)((uint64_t)close + UINT64_C(1));
                        }
                    }
                    int64_t value_39 = (int64_t)(source).length;
                    if (close >= value_39) {
                        result.error = SourceError_Unterminated;
                        return result;
                    }
                    compiler_source_Put(output, &(used), 34);
                    cursor = body;
                    while (cursor < close) {
                        compiler_source_PutRaw(output, &(used), (uint8_t)ZIRAN_INDEX(source.data, source.length, cursor));
                        cursor = (int64_t)((uint64_t)cursor + UINT64_C(1));
                    }
                    compiler_source_Put(output, &(used), 34);
                    while (at < close) {
                        if ((uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 10) {
                            line = (int32_t)((uint32_t)line + 1u);
                            gaps = (int64_t)((uint64_t)gaps + UINT64_C(1));
                        }
                        at = (int64_t)((uint64_t)at + UINT64_C(1));
                    }
                    column = (int32_t)((uint32_t)((int64_t)(marker).length) + 1u);
                    at = (int64_t)((uint64_t)at + (uint64_t)((int64_t)(marker).length));
                    continue;
                }
            }
            compiler_source_PutScanned(output, &(used), byte, &(gaps));
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        } else if (quote != 0) {
            compiler_source_PutScanned(output, &(used), byte, &(gaps));
            at = (int64_t)((uint64_t)at + UINT64_C(1));
            bool value_40 = byte == 92;
            if (value_40) {
                int64_t value_41 = (int64_t)(source).length;
                value_40 = (at < value_41);
            }
            if (value_40) {
                column = (int32_t)((uint32_t)column + 1u);
                byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
                compiler_source_PutScanned(output, &(used), byte, &(gaps));
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            } else if (byte == quote) {
                quote = 0;
            }
        } else {
            compiler_source_PutScanned(output, &(used), byte, &(gaps));
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        if (byte == 10) {
            line = (int32_t)((uint32_t)line + 1u);
            column = 1;
            line_comment = false;
        } else {
            column = (int32_t)((uint32_t)column + 1u);
        }
    }
    result.count = used;
    return result;
}

CommentScan
compiler_source_StripComments(String source, Slice output, int32_t depth)
{
    int64_t at = 0LL;
    int64_t used = 0LL;
    uint8_t quote = 0;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (depth > 0) {
            if (compiler_source_Matches(source, at, StringLiteral("/*"))) {
                depth = (int32_t)((uint32_t)depth + 1u);
                at = (int64_t)((uint64_t)at + UINT64_C(2));
            } else if (compiler_source_Matches(source, at, StringLiteral("*/"))) {
                depth = (int32_t)((uint32_t)depth - 1u);
                at = (int64_t)((uint64_t)at + UINT64_C(2));
                if (depth == 0) {
                    compiler_source_Put(output, &(used), 32);
                }
            } else {
                if (byte == 10) {
                    compiler_source_Put(output, &(used), byte);
                }
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            }
        } else if (quote != 0) {
            compiler_source_Put(output, &(used), byte);
            at = (int64_t)((uint64_t)at + UINT64_C(1));
            bool value_1 = byte == 92;
            if (value_1) {
                int64_t value_2 = (int64_t)(source).length;
                value_1 = (at < value_2);
            }
            if (value_1) {
                compiler_source_Put(output, &(used), (uint8_t)ZIRAN_INDEX(source.data, source.length, at));
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            } else if (byte == quote || byte == 10) {
                quote = 0;
            }
        } else if (byte == 34 || byte == 39) {
            quote = byte;
            compiler_source_Put(output, &(used), byte);
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        } else if (compiler_source_Matches(source, at, StringLiteral("//"))) {
            while (true) {
                int64_t value_3 = (int64_t)(source).length;
                if (!(at < value_3 && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 10)) { break; }
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            }
        } else if (compiler_source_Matches(source, at, StringLiteral("/*"))) {
            depth = 1;
            at = (int64_t)((uint64_t)at + UINT64_C(2));
        } else {
            compiler_source_Put(output, &(used), byte);
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return (CommentScan){.count = used, .depth = depth};
}

int32_t
compiler_source_NetBlockBraces(String source)
{
    int64_t at = 0LL;
    int32_t parentheses = 0;
    int32_t result = 0;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 40 || byte == 91) {
            parentheses = (int32_t)((uint32_t)parentheses + 1u);
        } else if (byte == 41 || byte == 93) {
            if (parentheses > 0) {
                parentheses = (int32_t)((uint32_t)parentheses - 1u);
            }
        } else if (parentheses == 0) {
            if (byte == 123) {
                result = (int32_t)((uint32_t)result + 1u);
            } else if (byte == 125) {
                result = (int32_t)((uint32_t)result - 1u);
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return result;
}

int64_t
compiler_source_StatementSeparator(String source)
{
    int64_t at = 0LL;
    int32_t parentheses = 0;
    int32_t brackets = 0;
    int32_t braces = 0;
    int64_t first_brace = compiler_source_Find(source, StringLiteral("{"));
    int64_t conditional = compiler_source_Find(source, StringLiteral("#ifx"));
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 40) {
            parentheses = (int32_t)((uint32_t)parentheses + 1u);
        } else if (byte == 41) {
            parentheses = (int32_t)((uint32_t)parentheses - 1u);
        } else if (byte == 91) {
            brackets = (int32_t)((uint32_t)brackets + 1u);
        } else if (byte == 93) {
            brackets = (int32_t)((uint32_t)brackets - 1u);
        } else if (byte == 123) {
            braces = (int32_t)((uint32_t)braces + 1u);
        } else if (byte == 125 && braces > 0) {
            braces = (int32_t)((uint32_t)braces - 1u);
        } else if (byte == 59 && parentheses == 0 && brackets == 0 && braces == 0) {
            int64_t after = compiler_source_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)));
            int64_t value_1 = (int64_t)(source).length;
            bool value_2 = after < value_1;
            bool value_3 = value_2;
            if (value_3) {
                bool value_4 = compiler_source_StartsWord(source, StringLiteral("for"));
                value_3 = !(value_4 && (first_brace < 0LL || at < first_brace));
            }
            bool value_5 = value_3;
            bool value_6 = value_5;
            if (value_6) {
                bool value_7 = conditional >= 0LL && conditional < at;
                bool value_8 = value_7;
                if (value_8) {
                    String value_9 = source;
                    bool value_10 = compiler_source_StartsWord(StringRange(value_9, (int64_t)after, (int64_t)value_9.length), StringLiteral("else"));
                    value_8 = value_10;
                }
                value_6 = !value_8;
            }
            if (value_6) {
                return at;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return -1LL;
}

ControlBlock
compiler_source_SplitControlBlock(String source)
{
    ControlBlock result = {0};
    int64_t value_0 = (int64_t)(source).length;
    if (value_0 < 4LL) {
        return result;
    }
    int64_t control = 0LL;
    if ((uint8_t)ZIRAN_INDEX(source.data, source.length, 0) == 125) {
        int64_t after = compiler_source_SkipSpace(source, 1LL);
        String value_1 = source;
        bool value_2 = compiler_source_StartsWord(StringRange(value_1, (int64_t)after, (int64_t)value_1.length), StringLiteral("else"));
        if (value_2) {
            control = after;
        }
    }
    int64_t end = control;
    while (true) {
        int64_t value_3 = (int64_t)(source).length;
        bool value_4 = end < value_3;
        bool value_5 = value_4;
        if (value_5) {
            bool value_6 = compiler_source_SourceIdentifier((uint8_t)ZIRAN_INDEX(source.data, source.length, end));
            value_5 = value_6;
        }
        bool value_7 = value_5;
        if (value_7) {
            int64_t value_8 = (int64_t)((uint64_t)end - (uint64_t)control);
            value_7 = (value_8 < 15LL);
        }
        if (!value_7) { break; }
        end = (int64_t)((uint64_t)end + UINT64_C(1));
    }
    String value_9 = source;
    String word = StringRange(value_9, (int64_t)control, (int64_t)end);
    bool value_10 = !StringEqual(word, StringLiteral("if")) && !StringEqual(word, StringLiteral("else")) && !StringEqual(word, StringLiteral("while"));
    bool value_11 = value_10 && !StringEqual(word, StringLiteral("for")) && !StringEqual(word, StringLiteral("defer"));
    bool value_12 = value_11 && !StringEqual(word, StringLiteral("switch")) && !StringEqual(word, StringLiteral("case"));
    bool value_13 = value_12 && !StringEqual(word, StringLiteral("guard")) && !StringEqual(word, StringLiteral("do"));
    if (value_13) {
        return result;
    }
    int64_t at = 0LL;
    int32_t parentheses = 0;
    int32_t expressions = 0;
    int64_t opening = 0LL;
    while (true) {
        int64_t value_14 = (int64_t)(source).length;
        if (!(at < value_14)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 40 || byte == 91) {
            parentheses = (int32_t)((uint32_t)parentheses + 1u);
        } else if (byte == 41 || byte == 93) {
            parentheses = (int32_t)((uint32_t)parentheses - 1u);
        } else if (byte == 123 && parentheses == 0) {
            int64_t before = at;
            while (true) {
                bool value_15 = before > 0LL;
                bool value_16 = value_15;
                if (value_16) {
                    bool value_17 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)before - UINT64_C(1)))));
                    value_16 = value_17;
                }
                if (!value_16) { break; }
                before = (int64_t)((uint64_t)before - UINT64_C(1));
            }
            bool value_18 = expressions > 0;
            if (!value_18) {
                bool value_19 = before > 0LL;
                if (value_19) {
                    bool value_20 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)before - UINT64_C(1)))) == 46;
                    value_19 = value_20;
                }
                bool value_21 = value_19;
                if (value_21) {
                    bool value_22 = before < 2LL;
                    if (!value_22) {
                        bool value_23 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)before - UINT64_C(2)))) != 46;
                        value_22 = value_23;
                    }
                    value_21 = value_22;
                }
                value_18 = value_21;
            }
            if (value_18) {
                expressions = (int32_t)((uint32_t)expressions + 1u);
            } else {
                opening = at;
                break;
            }
        } else if (byte == 125 && parentheses == 0 && expressions > 0) {
            expressions = (int32_t)((uint32_t)expressions - 1u);
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    if (opening == 0LL || expressions != 0) {
        return result;
    }
    int32_t depth = 1;
    at = (int64_t)((uint64_t)opening + UINT64_C(1));
    while (true) {
        int64_t value_24 = (int64_t)(source).length;
        if (!(at < value_24)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 123) {
            depth = (int32_t)((uint32_t)depth + 1u);
        } else if (byte == 125) {
            depth = (int32_t)((uint32_t)depth - 1u);
            if (depth == 0) {
                break;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    int64_t value_25 = (int64_t)(source).length;
    if (at >= value_25) {
        return result;
    }
    int64_t tail = compiler_source_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)));
    if (compiler_source_Byte(source, tail) == 59) {
        tail = compiler_source_SkipSpace(source, (int64_t)((uint64_t)tail + UINT64_C(1)));
    }
    int64_t value_26 = (int64_t)(source).length;
    bool value_27 = tail < value_26;
    bool value_28 = value_27;
    if (value_28) {
        bool value_29 = StringEqual(word, StringLiteral("do")) || StringEqual(word, StringLiteral("case")) || StringEqual(word, StringLiteral("guard"));
        bool value_30 = value_29;
        bool value_31 = value_30;
        if (!value_31) {
            String value_32 = source;
            bool value_33 = compiler_source_StartsWord(StringRange(value_32, (int64_t)tail, (int64_t)value_32.length), StringLiteral("else"));
            value_31 = (value_33 && !StringEqual(word, StringLiteral("if")) && !StringEqual(word, StringLiteral("else")));
        }
        value_28 = value_31;
    }
    if (value_28) {
        return result;
    }
    return (ControlBlock){.valid = true, .head_end = (int64_t)((uint64_t)opening + UINT64_C(1)), .body_begin = (int64_t)((uint64_t)opening + UINT64_C(1)), .body_end = at, .tail_begin = tail};
}

int64_t
compiler_source_ClosingParenthesis(String source)
{
    int64_t value_0 = (int64_t)(source).length;
    if (value_0 == 0LL || (uint8_t)ZIRAN_INDEX(source.data, source.length, 0) != 40) {
        return -1LL;
    }
    int32_t depth = 0;
    int64_t at = 0LL;
    while (true) {
        int64_t value_1 = (int64_t)(source).length;
        if (!(at < value_1)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 40) {
            depth = (int32_t)((uint32_t)depth + 1u);
        } else if (byte == 41) {
            depth = (int32_t)((uint32_t)depth - 1u);
            if (depth == 0) {
                return at;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return -1LL;
}

ProcedureHeader
compiler_source_ProcedureHeaderParts(String source)
{
    ProcedureHeader header = {.name = StringLiteral(""), .parameters = StringLiteral(""), .result = StringLiteral("void")};
    int64_t colons = compiler_source_Find(source, StringLiteral("::"));
    if (colons >= 0LL) {
        int64_t begin = 0LL;
        while (true) {
            bool value_0 = begin < colons;
            if (value_0) {
                bool value_1 = (uint8_t)ZIRAN_INDEX(source.data, source.length, begin) == 32 || (uint8_t)ZIRAN_INDEX(source.data, source.length, begin) == 9;
                value_0 = value_1;
            }
            if (!value_0) { break; }
            begin = (int64_t)((uint64_t)begin + UINT64_C(1));
        }
        int64_t end = begin;
        while (true) {
            bool value_2 = end < colons;
            bool value_3 = value_2;
            if (value_3) {
                bool value_4 = compiler_source_SourceIdentifier((uint8_t)ZIRAN_INDEX(source.data, source.length, end));
                value_3 = value_4;
            }
            if (!value_3) { break; }
            end = (int64_t)((uint64_t)end + UINT64_C(1));
        }
        String value_5 = source;
        header.name = StringRange(value_5, (int64_t)begin, (int64_t)end);
    }
    int64_t opening = compiler_source_Find(source, StringLiteral("("));
    if (opening < 0LL) {
        return header;
    }
    String value_6 = source;
    int64_t value_7 = compiler_source_ClosingParenthesis(StringRange(value_6, (int64_t)opening, (int64_t)value_6.length));
    int64_t closing = value_7;
    if (closing < 0LL) {
        return header;
    }
    closing = (int64_t)((uint64_t)closing + (uint64_t)opening);
    int64_t end = closing;
    while (true) {
        int64_t value_8 = (int64_t)((uint64_t)opening + UINT64_C(1));
        bool value_9 = end > value_8;
        bool value_10 = value_9;
        if (value_10) {
            bool value_11 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_10 = value_11;
        }
        if (!value_10) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    String value_12 = source;
    header.parameters = StringRange(value_12, (int64_t)((int64_t)((uint64_t)opening + UINT64_C(1))), (int64_t)end);
    int64_t at = (int64_t)((uint64_t)closing + UINT64_C(1));
    while (true) {
        int64_t value_13 = (int64_t)(source).length;
        bool value_14 = at < value_13;
        if (value_14) {
            bool value_15 = (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 32 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 9;
            value_14 = value_15;
        }
        if (!value_14) { break; }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    bool value_16 = compiler_source_Matches(source, at, StringLiteral("->"));
    if (!value_16) {
        return header;
    }
    at = (int64_t)((uint64_t)at + UINT64_C(2));
    while (true) {
        int64_t value_17 = (int64_t)(source).length;
        bool value_18 = at < value_17;
        if (value_18) {
            bool value_19 = (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 32 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 9;
            value_18 = value_19;
        }
        if (!value_18) { break; }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    end = at;
    while (true) {
        int64_t value_20 = (int64_t)(source).length;
        bool value_21 = end < value_20 && (uint8_t)ZIRAN_INDEX(source.data, source.length, end) != 35 && (uint8_t)ZIRAN_INDEX(source.data, source.length, end) != 123;
        if (!value_21) { break; }
        end = (int64_t)((uint64_t)end + UINT64_C(1));
    }
    while (true) {
        bool value_22 = end > at;
        bool value_23 = value_22;
        if (value_23) {
            bool value_24 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_23 = value_24;
        }
        if (!value_23) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    String value_25 = source;
    header.result = StringRange(value_25, (int64_t)at, (int64_t)end);
    return header;
}

int64_t
compiler_source_NormalizeTypeSpacing(String source, Slice output)
{
    int64_t used = 0LL;
    int64_t at = 0LL;
    bool quoted = false;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        compiler_source_Put(output, &(used), byte);
        at = (int64_t)((uint64_t)at + UINT64_C(1));
        if (quoted) {
            bool value_1 = byte == 92;
            if (value_1) {
                int64_t value_2 = (int64_t)(source).length;
                value_1 = (at < value_2);
            }
            if (value_1) {
                compiler_source_Put(output, &(used), (uint8_t)ZIRAN_INDEX(source.data, source.length, at));
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            } else if (byte == 34) {
                quoted = false;
            }
        } else if (byte == 34) {
            quoted = true;
        } else if (byte == 93 || byte == 42) {
            int64_t next = at;
            while (true) {
                int64_t value_3 = (int64_t)(source).length;
                bool value_4 = next < value_3;
                if (value_4) {
                    bool value_5 = (uint8_t)ZIRAN_INDEX(source.data, source.length, next) == 32 || (uint8_t)ZIRAN_INDEX(source.data, source.length, next) == 9;
                    value_4 = value_5;
                }
                if (!value_4) { break; }
                next = (int64_t)((uint64_t)next + UINT64_C(1));
            }
            uint8_t following = compiler_source_Byte(source, next);
            bool value_6 = next > at;
            bool value_7 = value_6;
            if (value_7) {
                bool value_8 = compiler_source_Letter(following);
                value_7 = (value_8 || following == 91 || following == 36);
            }
            if (value_7) {
                at = next;
            }
        }
    }
    return used;
}

int64_t
compiler_source_CopyProcedureText(String source, Slice output, bool normalize_type)
{
    int64_t value_0 = (int64_t)(output).length;
    if (value_0 == 0LL) {
        return 0LL;
    }
    int64_t count = (int64_t)(source).length;
    int64_t value_1 = (int64_t)(output).length;
    if (count >= value_1) {
        count = (int64_t)((uint64_t)((int64_t)(output).length) - UINT64_C(1));
    }
    int64_t used = 0LL;
    if (normalize_type) {
        while (true) {
            bool value_2 = count > 0LL;
            bool value_3 = value_2;
            if (value_3) {
                bool value_4 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)count - UINT64_C(1)))));
                value_3 = value_4;
            }
            if (!value_3) { break; }
            count = (int64_t)((uint64_t)count - UINT64_C(1));
        }
        String value_5 = source;
        Slice value_6 = output;
        int64_t value_7 = compiler_source_NormalizeTypeSpacing(StringRange(value_5, (int64_t)0LL, (int64_t)count), SliceRange(value_6, (int64_t)0LL, (int64_t)count, sizeof(uint8_t)));
        used = value_7;
    } else {
        {
            int64_t range_first_15 = 0LL;
            int64_t range_last_15 = (int64_t)((uint64_t)count - UINT64_C(1));
            int64_t index = range_first_15;
            while (index <= range_last_15) {
                ((uint8_t *)output.data)[SliceIndex(output, (int64_t)index)] = (uint8_t)ZIRAN_INDEX(source.data, source.length, index);
                if (index == range_last_15) {
                    break;
                }
                index = (int64_t)((uint64_t)index + UINT64_C(1));
            }
        }
        used = count;
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = 0;
    return used;
}

bool
compiler_source_BraceOutsideLiterals(String source)
{
    int64_t at = 0LL;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 92) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
            int64_t value_1 = (int64_t)(source).length;
            if (at < value_1) {
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            }
        } else if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
        } else if (byte == 123) {
            return true;
        } else {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return false;
}

bool
compiler_source_LooksLikeProcedureHeader(String source)
{
    bool value_0 = compiler_source_StartsWord(source, StringLiteral("#import"));
    bool value_1 = value_0;
    if (!value_1) {
        bool value_2 = compiler_source_Matches(source, 0LL, StringLiteral("#import,"));
        value_1 = value_2;
    }
    if (value_1) {
        return false;
    }
    int64_t colons = compiler_source_Find(source, StringLiteral("::"));
    if (colons < 0LL) {
        return false;
    }
    int64_t at = compiler_source_SkipSpace(source, (int64_t)((uint64_t)colons + UINT64_C(2)));
    int64_t end = (int64_t)(source).length;
    while (true) {
        bool value_3 = end > at;
        bool value_4 = value_3;
        if (value_4) {
            bool value_5 = compiler_source_Space((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_4 = value_5;
        }
        if (!value_4) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    String value_6 = source;
    String body = StringRange(value_6, (int64_t)at, (int64_t)end);
    if (compiler_source_StartsWord(body, StringLiteral("#as"))) {
        String value_7 = body;
        int64_t value_8 = compiler_source_SkipSpace(body, 3LL);
        body = StringRange(value_7, (int64_t)value_8, (int64_t)value_7.length);
    }
    bool value_9 = compiler_source_StartsWord(body, StringLiteral("#import"));
    bool value_10 = value_9;
    if (!value_10) {
        bool value_11 = compiler_source_Matches(body, 0LL, StringLiteral("#import,"));
        value_10 = value_11;
    }
    bool value_12 = value_10;
    if (!value_12) {
        bool value_13 = compiler_source_StartsWord(body, StringLiteral("#defined"));
        value_12 = value_13;
    }
    bool value_14 = value_12;
    if (!value_14) {
        bool value_15 = compiler_source_StartsWord(body, StringLiteral("#define"));
        value_14 = value_15;
    }
    bool value_16 = value_14;
    if (!value_16) {
        bool value_17 = compiler_source_StartsWord(body, StringLiteral("struct"));
        value_16 = value_17;
    }
    bool value_18 = value_16;
    if (!value_18) {
        bool value_19 = compiler_source_StartsWord(body, StringLiteral("enum"));
        value_18 = value_19;
    }
    bool value_20 = value_18;
    if (!value_20) {
        bool value_21 = compiler_source_StartsWord(body, StringLiteral("union"));
        value_20 = value_21;
    }
    bool value_22 = value_20;
    if (!value_22) {
        int64_t value_23 = compiler_source_Find(body, StringLiteral("#type"));
        value_22 = (value_23 >= 0LL);
    }
    bool value_24 = value_22;
    if (!value_24) {
        bool value_25 = compiler_source_Byte(body, 0LL) != 40;
        value_24 = value_25;
    }
    if (value_24) {
        return false;
    }
    int64_t value_26 = compiler_source_Find(body, StringLiteral("{"));
    bool value_27 = value_26 >= 0LL;
    if (!value_27) {
        int64_t value_28 = compiler_source_Find(body, StringLiteral("->"));
        value_27 = (value_28 >= 0LL);
    }
    if (value_27) {
        return true;
    }
    int32_t depth = 0;
    int64_t begin = -1LL;
    end = -1LL;
    at = 0LL;
    while (true) {
        int64_t value_29 = (int64_t)(body).length;
        if (!(at < value_29)) { break; }
        if ((uint8_t)ZIRAN_INDEX(body.data, body.length, at) == 40) {
            if (depth == 0) {
                begin = (int64_t)((uint64_t)at + UINT64_C(1));
            }
            depth = (int32_t)((uint32_t)depth + 1u);
        } else if ((uint8_t)ZIRAN_INDEX(body.data, body.length, at) == 41) {
            depth = (int32_t)((uint32_t)depth - 1u);
            if (depth == 0) {
                end = at;
                break;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    if (begin < 0LL || end < 0LL) {
        return false;
    }
    while (true) {
        bool value_30 = begin < end;
        if (value_30) {
            bool value_31 = (uint8_t)ZIRAN_INDEX(body.data, body.length, begin) == 32 || (uint8_t)ZIRAN_INDEX(body.data, body.length, begin) == 9;
            value_30 = value_31;
        }
        if (!value_30) { break; }
        begin = (int64_t)((uint64_t)begin + UINT64_C(1));
    }
    if (begin >= end) {
        return true;
    }
    uint8_t byte = (uint8_t)ZIRAN_INDEX(body.data, body.length, begin);
    if (byte == 34 || byte == 39 || (byte >= 48 && byte <= 57)) {
        return false;
    }
    String value_32 = body;
    int64_t value_33 = compiler_source_Find(StringRange(value_32, (int64_t)begin, (int64_t)value_32.length), StringLiteral("\?"));
    bool value_34 = value_33 < 0LL;
    if (value_34) {
        String value_35 = body;
        int64_t value_36 = compiler_source_Find(StringRange(value_35, (int64_t)begin, (int64_t)value_35.length), StringLiteral(":"));
        value_34 = (value_36 >= 0LL);
    }
    return value_34;
}

ControlBlock
compiler_source_SplitProcedureBody(String source)
{
    ControlBlock block = {0};
    int64_t opening = compiler_source_Find(source, StringLiteral("{"));
    bool value_0 = opening < 0LL;
    if (!value_0) {
        bool value_1 = compiler_source_Byte(source, (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1))) != 125;
        value_0 = value_1;
    }
    bool value_2 = value_0;
    if (!value_2) {
        bool value_3 = compiler_source_LooksLikeProcedureHeader(source);
        value_2 = !value_3;
    }
    if (value_2) {
        return block;
    }
    int32_t depth = 0;
    int64_t at = opening;
    while (true) {
        int64_t value_4 = (int64_t)(source).length;
        if (!(at < value_4)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_source_AfterQuote(source, at);
            continue;
        }
        if (byte == 123) {
            depth = (int32_t)((uint32_t)depth + 1u);
        } else if (byte == 125) {
            depth = (int32_t)((uint32_t)depth - 1u);
            bool value_5 = depth < 0;
            if (!value_5) {
                bool value_6 = depth == 0;
                if (value_6) {
                    int64_t value_7 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1));
                    value_6 = (at != value_7);
                }
                value_5 = value_6;
            }
            if (value_5) {
                return block;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    if (depth != 0) {
        return block;
    }
    return (ControlBlock){.valid = true, .head_end = (int64_t)((uint64_t)opening + UINT64_C(1)), .body_begin = (int64_t)((uint64_t)opening + UINT64_C(1)), .body_end = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1)), .tail_begin = (int64_t)(source).length};
}

MustUseModifier
compiler_source_ProcedureMustUse(String source, String result_type)
{
    int64_t opening = compiler_source_Find(source, StringLiteral("("));
    if (opening < 0LL) {
        return MustUseModifier_None;
    }
    String value_0 = source;
    int64_t value_1 = compiler_source_ClosingParenthesis(StringRange(value_0, (int64_t)opening, (int64_t)value_0.length));
    int64_t closing = value_1;
    if (closing < 0LL) {
        return MustUseModifier_None;
    }
    closing = (int64_t)((uint64_t)closing + (uint64_t)opening);
    String value_2 = source;
    String value_3 = StringRange(value_2, (int64_t)((int64_t)((uint64_t)closing + UINT64_C(1))), (int64_t)value_2.length);
    String tail = value_3;
    int64_t end = compiler_source_Find(tail, StringLiteral("{"));
    if (end < 0LL) {
        end = compiler_source_Find(tail, StringLiteral(";"));
    }
    if (end < 0LL) {
        end = (int64_t)(tail).length;
    }
    int32_t count = 0;
    int64_t at = 0LL;
    while (at < end) {
        if ((uint8_t)ZIRAN_INDEX(tail.data, tail.length, at) == 34) {
            String value_4 = tail;
            at = compiler_source_AfterQuote(StringRange(value_4, (int64_t)0LL, (int64_t)end), at);
        } else {
            String value_5 = tail;
            bool value_6 = compiler_source_Matches(StringRange(value_5, (int64_t)0LL, (int64_t)end), at, StringLiteral("#must"));
            bool value_7 = value_6;
            if (value_7) {
                bool value_8 = compiler_source_SourceIdentifier(compiler_source_Byte(tail, (int64_t)((uint64_t)at + UINT64_C(5))));
                value_7 = !value_8;
            }
            if (value_7) {
                int64_t after = compiler_source_SkipSpace(tail, (int64_t)((uint64_t)at + UINT64_C(5)));
                if (after < end && (uint8_t)ZIRAN_INDEX(tail.data, tail.length, after) != 35) {
                    return MustUseModifier_Arguments;
                }
                count = (int32_t)((uint32_t)count + 1u);
                at = (int64_t)((uint64_t)at + UINT64_C(5));
            } else {
                at = (int64_t)((uint64_t)at + UINT64_C(1));
            }
        }
    }
    if (count > 1) {
        return MustUseModifier_Duplicate;
    }
    if (count == 0) {
        return MustUseModifier_None;
    }
    if (StringEqual(result_type, StringLiteral("void"))) {
        return MustUseModifier_NoResult;
    }
    return MustUseModifier_Required;
}
