/* Generated by zi2c from compiler_source.zi. */
#ifndef ZIRAN_COMPILER_SOURCE_H
#define ZIRAN_COMPILER_SOURCE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_slice.h"
#include "zir_string.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef int32_t SourceError;
typedef struct SourceRewrite SourceRewrite;
typedef struct CommentScan CommentScan;
typedef struct ControlBlock ControlBlock;

enum {
    SourceError_None = 0,
    SourceError_Delimiter = 1,
    SourceError_DelimiterLine = 2,
    SourceError_Unterminated = 3,
};

struct SourceRewrite {
    SourceError error;
    int64_t count;
    int32_t line;
    int32_t column;
    int64_t marker_begin;
    int64_t marker_end;
};

struct CommentScan {
    int64_t count;
    int32_t depth;
};

struct ControlBlock {
    bool valid;
    int64_t head_end;
    int64_t body_begin;
    int64_t body_end;
    int64_t tail_begin;
};
bool compiler_source_SourceIdentifier(uint8_t byte);
bool compiler_source_StartsWord(String source, String word);
bool compiler_source_IdentifierText(String source, bool member_path);
bool compiler_source_ContainsDirective(String source, String directive);
SourceRewrite compiler_source_RewriteRawStrings(String source, Slice output, int64_t marker_limit);
CommentScan compiler_source_StripComments(String source, Slice output, int32_t depth);
int32_t compiler_source_NetBlockBraces(String source);
int64_t compiler_source_StatementSeparator(String source);
ControlBlock compiler_source_SplitControlBlock(String source);
int64_t compiler_source_ClosingParenthesis(String source);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_SOURCE_H */
