/* Generated by zi2c from compiler_enum.zi. */
#define ZIRAN_COMPILER_ENUM_H_PRIVATE 1
#include "compiler_enum.h"
#undef ZIRAN_COMPILER_ENUM_H_PRIVATE
#include <stdint.h>
#include <stdlib.h>

/* SignedBits reads the low w bits of x as a signed number. */
static inline int64_t SignedBits(uint64_t x, int w) {
    uint64_t mask = w == 64 ? UINT64_MAX : (UINT64_C(1) << w) - 1;
    x &= mask;
    return x <= (mask >> 1) ? (int64_t)x : -1 - (int64_t)(mask - x);
}

/* IntegerOp applies op to the low w bits of a and b: 0 convert, 1 add,
 * 2 subtract, 3 multiply, 4 divide, 5 remainder, 6 shift left,
 * 7 shift right, 8 and, 9 or, 10 xor. Division by zero and
 * out-of-range shifts abort. */
static inline uint64_t IntegerOp(uint64_t a, uint64_t b, int w, int sign, int op) {
    uint64_t mask = w == 64 ? UINT64_MAX : (UINT64_C(1) << w) - 1;
    uint64_t shift = b;
    a &= mask;
    b &= mask;
    switch(op) {
    case 0: return a;
    case 1: return (a + b) & mask;
    case 2: return (a - b) & mask;
    case 3: return (a * b) & mask;
    case 4: case 5:
        if(!b) abort();
        if(sign) {
            int64_t x = SignedBits(a, w), y = SignedBits(b, w);
            if(x == INT64_MIN && y == -1) return op == 4 ? a : 0;
            return (uint64_t)(op == 4 ? x / y : x % y) & mask;
        }
        return op == 4 ? a / b : a % b;
    case 6: case 7:
        if(shift >= (uint64_t)w) abort();
        if(op == 6) return (a << shift) & mask;
        if(!shift) return a;
        return (a >> shift) |
            ((sign && (a & (UINT64_C(1) << (w - 1)))) ? mask ^ (mask >> shift) : 0);
    case 8: return a & b;
    case 9: return a | b;
    case 10: return a ^ b;
    default: abort();
    }
    return 0;
}
static void compiler_enum_Space(Cursor* cursor);
static bool compiler_enum_IdentifierStart(uint8_t byte);
static int64_t compiler_enum_Digit(uint8_t byte);
static int64_t compiler_enum_Number(Cursor* cursor, bool negative);
static int64_t compiler_enum_Term(Cursor* cursor, Slice entries);
static int64_t compiler_enum_Product(Cursor* cursor, Slice entries);
static int64_t compiler_enum_Sum(Cursor* cursor, Slice entries);
static int64_t compiler_enum_Expression(Cursor* cursor, Slice entries);

static void
compiler_enum_Space(Cursor* cursor)
{
    int64_t value_0 = compiler_text_SkipSpace(cursor->source, cursor->at, false);
    cursor->at = value_0;
}

static bool
compiler_enum_IdentifierStart(uint8_t byte)
{
    return byte == 95 || (byte >= 97 && byte <= 122) || (byte >= 65 && byte <= 90);
}

static int64_t
compiler_enum_Digit(uint8_t byte)
{
    if (byte >= 48 && byte <= 57) {
        return (int64_t)(((uint8_t)((uint32_t)byte - 48u)));
    }
    if (byte >= 97 && byte <= 102) {
        return (int64_t)((uint64_t)(((uint8_t)((uint32_t)byte - 97u))) + UINT64_C(10));
    }
    if (byte >= 65 && byte <= 70) {
        return (int64_t)((uint64_t)(((uint8_t)((uint32_t)byte - 65u))) + UINT64_C(10));
    }
    return -1LL;
}

static int64_t
compiler_enum_Number(Cursor* cursor, bool negative)
{
    uint64_t base = 10ULL;
    if ((uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at) == 48) {
        base = 8ULL;
        int64_t value_0 = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
        int64_t value_1 = (int64_t)(cursor->source).length;
        bool value_2 = value_0 < value_1;
        if (value_2) {
            bool value_3 = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, ((int64_t)((uint64_t)(cursor->at) + UINT64_C(1)))) == 120;
            bool value_4 = value_3;
            if (!value_4) {
                bool value_5 = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, ((int64_t)((uint64_t)(cursor->at) + UINT64_C(1)))) == 88;
                value_4 = value_5;
            }
            value_2 = value_4;
        }
        if (value_2) {
            base = 16ULL;
            cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(2));
        }
    }
    int64_t begin = cursor->at;
    uint64_t limit = 9223372036854775807ULL;
    if (negative) {
        limit = (uint64_t)((uint64_t)limit + UINT64_C(1));
    }
    uint64_t magnitude = 0ULL;
    while (true) {
        int64_t value_6 = cursor->at;
        int64_t value_7 = (int64_t)(cursor->source).length;
        if (!(value_6 < value_7)) { break; }
        int64_t digit = compiler_enum_Digit((uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at));
        bool value_8 = digit < 0LL;
        if (!value_8) {
            uint64_t value_9 = (uint64_t)(digit);
            value_8 = (value_9 >= base);
        }
        if (value_8) {
            break;
        }
        uint64_t value_10 = (uint64_t)(IntegerOp((uint64_t)(((uint64_t)((uint64_t)limit - (uint64_t)(digit)))), (uint64_t)(base), 64, 0, 4));
        if (magnitude > value_10) {
            cursor->valid = false;
            return 0LL;
        }
        magnitude = (uint64_t)(((uint64_t)magnitude * (uint64_t)base) + (uint64_t)(digit));
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
    }
    int64_t value_11 = cursor->at;
    if (value_11 == begin) {
        cursor->valid = false;
        return 0LL;
    }
    if (negative) {
        return (int64_t)(((uint64_t)(UINT64_C(0) - (uint64_t)magnitude)));
    }
    return (int64_t)(magnitude);
}

static int64_t
compiler_enum_Term(Cursor* cursor, Slice entries)
{
    compiler_enum_Space(cursor);
    bool negative = false;
    int64_t value_0 = cursor->at;
    int64_t value_1 = (int64_t)(cursor->source).length;
    bool value_2 = value_0 < value_1;
    if (value_2) {
        bool value_3 = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at) == 43 || (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at) == 45;
        value_2 = value_3;
    }
    if (value_2) {
        negative = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at) == 45;
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
    }
    compiler_enum_Space(cursor);
    int64_t value_4 = cursor->at;
    int64_t value_5 = (int64_t)(cursor->source).length;
    if (value_4 == value_5) {
        cursor->valid = false;
        return 0LL;
    }
    uint8_t first = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at);
    if (first >= 48 && first <= 57) {
        return compiler_enum_Number(cursor, negative);
    }
    bool value_6 = compiler_enum_IdentifierStart(first);
    if (!value_6) {
        cursor->valid = false;
        return 0LL;
    }
    int64_t begin = cursor->at;
    while (true) {
        int64_t value_7 = cursor->at;
        int64_t value_8 = (int64_t)(cursor->source).length;
        bool value_9 = value_7 < value_8;
        bool value_10 = value_9;
        if (value_10) {
            bool value_11 = compiler_text_IdentifierByte((uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at));
            value_10 = value_11;
        }
        if (!value_10) { break; }
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
    }
    String value_12 = cursor->source;
    String name = StringRange(value_12, (int64_t)begin, (int64_t)cursor->at);
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_13 = (int64_t)(entries).length;
            if (!(it_index < value_13)) { break; }
            Entry entry = ((Entry *)entries.data)[SliceIndex(entries, (int64_t)it_index)];
            if (StringEqual(entry.name, name)) {
                if (!negative) {
                    return entry.value;
                }
                int64_t value_14 = entry.value;
                int64_t value_15 = -INT64_C(9223372036854775807)-1;
                if (value_14 == value_15) {
                    cursor->valid = false;
                    return 0LL;
                }
                return (int64_t)(UINT64_C(0) - (uint64_t)(entry.value));
            }
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
    cursor->valid = false;
    return 0LL;
}

static int64_t
compiler_enum_Product(Cursor* cursor, Slice entries)
{
    int64_t value = compiler_enum_Term(cursor, entries);
    while (cursor->valid) {
        compiler_enum_Space(cursor);
        int64_t value_0 = cursor->at;
        int64_t value_1 = (int64_t)(cursor->source).length;
        if (value_0 == value_1) {
            return value;
        }
        uint8_t op = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at);
        if (op != 42 && op != 47 && op != 37) {
            return value;
        }
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
        int64_t right = compiler_enum_Term(cursor, entries);
        if (!cursor->valid) {
            return 0LL;
        }
        if (op == 42) {
            bool value_2 = value > 0LL && right > 0LL;
            if (value_2) {
                int64_t value_3 = (int64_t)SignedBits(IntegerOp((uint64_t)(9223372036854775807LL), (uint64_t)(right), 64, 1, 4), 64);
                value_2 = (value > value_3);
            }
            bool value_4 = value_2;
            if (!value_4) {
                bool value_5 = value > 0LL && right < 0LL;
                if (value_5) {
                    int64_t value_6 = (int64_t)SignedBits(IntegerOp((uint64_t)((-INT64_C(9223372036854775807)-1)), (uint64_t)(value), 64, 1, 4), 64);
                    value_5 = (right < value_6);
                }
                value_4 = value_5;
            }
            bool value_7 = value_4;
            if (!value_7) {
                bool value_8 = value < 0LL && right > 0LL;
                if (value_8) {
                    int64_t value_9 = (int64_t)SignedBits(IntegerOp((uint64_t)((-INT64_C(9223372036854775807)-1)), (uint64_t)(right), 64, 1, 4), 64);
                    value_8 = (value < value_9);
                }
                value_7 = value_8;
            }
            bool value_10 = value_7;
            if (!value_10) {
                bool value_11 = value < 0LL && right < 0LL;
                if (value_11) {
                    int64_t value_12 = (int64_t)SignedBits(IntegerOp((uint64_t)(9223372036854775807LL), (uint64_t)(value), 64, 1, 4), 64);
                    value_11 = (right < value_12);
                }
                value_10 = value_11;
            }
            if (value_10) {
                cursor->valid = false;
                return 0LL;
            }
            value = (int64_t)((uint64_t)value * (uint64_t)right);
        } else {
            bool value_13 = right == 0LL;
            if (!value_13) {
                int64_t value_14 = -INT64_C(9223372036854775807)-1;
                value_13 = (value == value_14 && right == -1LL);
            }
            if (value_13) {
                cursor->valid = false;
                return 0LL;
            }
            if (op == 47) {
                value = (int64_t)SignedBits(IntegerOp((uint64_t)(value), (uint64_t)(right), 64, 1, 4), 64);
            } else {
                value = (int64_t)SignedBits(IntegerOp((uint64_t)(value), (uint64_t)(right), 64, 1, 5), 64);
            }
        }
    }
    return 0LL;
}

static int64_t
compiler_enum_Sum(Cursor* cursor, Slice entries)
{
    int64_t value = compiler_enum_Product(cursor, entries);
    while (cursor->valid) {
        compiler_enum_Space(cursor);
        int64_t value_0 = cursor->at;
        int64_t value_1 = (int64_t)(cursor->source).length;
        if (value_0 == value_1) {
            return value;
        }
        uint8_t op = (uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, cursor->at);
        if (op != 43 && op != 45) {
            return value;
        }
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
        int64_t right = compiler_enum_Product(cursor, entries);
        if (!cursor->valid) {
            return 0LL;
        }
        bool value_2 = op == 43;
        if (value_2) {
            bool value_3 = right > 0LL;
            if (value_3) {
                int64_t value_4 = (int64_t)(UINT64_C(9223372036854775807) - (uint64_t)right);
                value_3 = (value > value_4);
            }
            bool value_5 = value_3;
            if (!value_5) {
                bool value_6 = right < 0LL;
                if (value_6) {
                    int64_t value_7 = (int64_t)((uint64_t)((-INT64_C(9223372036854775807)-1)) - (uint64_t)right);
                    value_6 = (value < value_7);
                }
                value_5 = value_6;
            }
            value_2 = value_5;
        }
        bool value_8 = value_2;
        if (!value_8) {
            bool value_9 = op == 45;
            if (value_9) {
                bool value_10 = right < 0LL;
                if (value_10) {
                    int64_t value_11 = (int64_t)(UINT64_C(9223372036854775807) + (uint64_t)right);
                    value_10 = (value > value_11);
                }
                bool value_12 = value_10;
                if (!value_12) {
                    bool value_13 = right > 0LL;
                    if (value_13) {
                        int64_t value_14 = (int64_t)((uint64_t)((-INT64_C(9223372036854775807)-1)) + (uint64_t)right);
                        value_13 = (value < value_14);
                    }
                    value_12 = value_13;
                }
                value_9 = value_12;
            }
            value_8 = value_9;
        }
        if (value_8) {
            cursor->valid = false;
            return 0LL;
        }
        if (op == 43) {
            value = (int64_t)((uint64_t)value + (uint64_t)right);
        } else {
            value = (int64_t)((uint64_t)value - (uint64_t)right);
        }
    }
    return 0LL;
}

static int64_t
compiler_enum_Expression(Cursor* cursor, Slice entries)
{
    int64_t value = compiler_enum_Sum(cursor, entries);
    while (cursor->valid) {
        compiler_enum_Space(cursor);
        int64_t value_0 = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
        int64_t value_1 = (int64_t)(cursor->source).length;
        bool value_2 = value_0 >= value_1;
        if (!value_2) {
            String value_3 = cursor->source;
            bool value_4 = !StringEqual(StringRange(value_3, (int64_t)cursor->at, (int64_t)((int64_t)((uint64_t)(cursor->at) + UINT64_C(2)))), StringLiteral("<<"));
            value_2 = value_4;
        }
        if (value_2) {
            break;
        }
        cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(2));
        int64_t amount = compiler_enum_Sum(cursor, entries);
        bool value_5 = !cursor->valid || amount < 0LL || amount >= 63LL || value < 0LL;
        if (!value_5) {
            int64_t value_6 = (int64_t)SignedBits(IntegerOp((uint64_t)(9223372036854775807LL), (uint64_t)(amount), 64, 1, 7), 64);
            value_5 = (value > value_6);
        }
        if (value_5) {
            cursor->valid = false;
            return 0LL;
        }
        value = (int64_t)SignedBits(IntegerOp((uint64_t)(value), (uint64_t)(amount), 64, 1, 6), 64);
    }
    compiler_enum_Space(cursor);
    int64_t value_7 = cursor->at;
    int64_t value_8 = (int64_t)(cursor->source).length;
    if (value_7 != value_8) {
        cursor->valid = false;
    }
    return value;
}

bool
compiler_enum_FitsBacking(String backing, int64_t value)
{
    if (StringEqual(backing, StringLiteral("s64"))) {
        return true;
    }
    if (StringEqual(backing, StringLiteral("u64"))) {
        return value >= 0LL;
    }
    if (StringEqual(backing, StringLiteral("s8"))) {
        return value >= -128LL && value <= 127LL;
    }
    if (StringEqual(backing, StringLiteral("s16"))) {
        return value >= -32768LL && value <= 32767LL;
    }
    if (StringEqual(backing, StringLiteral("s32"))) {
        return value >= -2147483648LL && value <= 2147483647LL;
    }
    if (StringEqual(backing, StringLiteral("u8"))) {
        return value >= 0LL && value <= 255LL;
    }
    if (StringEqual(backing, StringLiteral("u16"))) {
        return value >= 0LL && value <= 65535LL;
    }
    if (StringEqual(backing, StringLiteral("u32"))) {
        return value >= 0LL && value <= 4294967295LL;
    }
    return false;
}

Evaluation
compiler_enum_MemberValue(String body, String backing, String wanted, Slice entries, int64_t name_limit)
{
    Evaluation result = {0};
    int64_t at = 0LL;
    int64_t next = 0LL;
    bool next_valid = true;
    while (true) {
        int64_t value_0 = (int64_t)(body).length;
        if (!(at < value_0)) { break; }
        while (true) {
            int64_t value_1 = (int64_t)(body).length;
            bool value_2 = at < value_1;
            bool value_3 = value_2;
            if (value_3) {
                bool value_4 = (uint8_t)ZIRAN_INDEX(body.data, body.length, at) == 44;
                bool value_5 = value_4;
                if (!value_5) {
                    bool value_6 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(body.data, body.length, at));
                    value_5 = value_6;
                }
                value_3 = value_5;
            }
            if (!value_3) { break; }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        int64_t value_7 = (int64_t)(body).length;
        if (at == value_7) {
            break;
        }
        int64_t end = at;
        while (true) {
            int64_t value_8 = (int64_t)(body).length;
            if (!(end < value_8 && (uint8_t)ZIRAN_INDEX(body.data, body.length, end) != 44 && (uint8_t)ZIRAN_INDEX(body.data, body.length, end) != 10)) { break; }
            end = (int64_t)((uint64_t)end + UINT64_C(1));
        }
        int64_t begin = at;
        bool value_9 = compiler_enum_IdentifierStart((uint8_t)ZIRAN_INDEX(body.data, body.length, at));
        if (!value_9) {
            return (Evaluation){0};
        }
        while (true) {
            bool value_10 = at < end;
            bool value_11 = value_10;
            if (value_11) {
                bool value_12 = compiler_text_IdentifierByte((uint8_t)ZIRAN_INDEX(body.data, body.length, at));
                value_11 = value_12;
            }
            if (!value_11) { break; }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        String value_13 = body;
        String name = StringRange(value_13, (int64_t)begin, (int64_t)at);
        int64_t value_14 = (int64_t)(name).length;
        bool value_15 = value_14 >= name_limit;
        if (!value_15) {
            int64_t value_16 = result.count;
            int64_t value_17 = (int64_t)(entries).length;
            value_15 = (value_16 >= value_17);
        }
        if (value_15) {
            return (Evaluation){0};
        }
        {
            Slice value_18 = entries;
            Slice value_19 = SliceRange(value_18, (int64_t)0LL, (int64_t)result.count, sizeof(Entry));
            Slice loop_view_26 = SliceRange(value_19, (int64_t)0, (int64_t)value_19.length, sizeof(Entry));
            int64_t loop_count_26 = (int64_t)(loop_view_26).length;
            int64_t loop_cursor_26 = 0LL;
            while (loop_cursor_26 < loop_count_26) {
                int64_t loop_index_26 = loop_cursor_26;
                Entry entry = ((Entry *)loop_view_26.data)[SliceIndex(loop_view_26, (int64_t)loop_index_26)];
                if (StringEqual(entry.name, name)) {
                    return (Evaluation){0};
                }
                loop_cursor_26 = (int64_t)((uint64_t)loop_cursor_26 + UINT64_C(1));
            }
        }
        String value_20 = body;
        Cursor cursor = {.source = StringRange(value_20, (int64_t)at, (int64_t)end), .at = 0LL, .valid = true};
        compiler_enum_Space(&(cursor));
        int64_t value = next;
        int64_t value_21 = cursor.at;
        int64_t value_22 = (int64_t)(cursor.source).length;
        if (value_21 < value_22) {
            if ((uint8_t)ZIRAN_INDEX(cursor.source.data, cursor.source.length, cursor.at) != 61) {
                return (Evaluation){0};
            }
            cursor.at = (int64_t)((uint64_t)(cursor.at) + UINT64_C(1));
            Slice value_23 = entries;
            value = compiler_enum_Expression(&(cursor), SliceRange(value_23, (int64_t)0LL, (int64_t)result.count, sizeof(Entry)));
            if (!cursor.valid) {
                return (Evaluation){0};
            }
        } else if (!next_valid) {
            return (Evaluation){0};
        }
        bool value_24 = compiler_enum_FitsBacking(backing, value);
        if (!value_24) {
            return (Evaluation){0};
        }
        ((Entry *)entries.data)[SliceIndex(entries, (int64_t)result.count)] = (Entry){.name = name, .value = value};
        if (StringEqual(name, wanted)) {
            result.found = true;
            result.value = value;
        }
        result.count = (int64_t)((uint64_t)(result.count) + UINT64_C(1));
        next_valid = value != 9223372036854775807LL;
        next = value;
        if (next_valid) {
            next = (int64_t)((uint64_t)next + UINT64_C(1));
        }
        at = end;
        int64_t value_25 = (int64_t)(body).length;
        if (at < value_25) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    int64_t value_26 = result.count;
    result.valid = value_26 > 0LL;
    return result;
}
