/*
 * k2c_lower.c - Kir → C backend. Lowers a KirProgram to .c/.h source files.
 *
 * This is the Kir-based path (gated by --kir). It currently produces
 * structurally valid C but does NOT yet reproduce kc's byte-for-byte output
 * (PushUIInspectSource wrapping, __auto_type temps, defer splicing, indent
 * recompute, rewrite_kry_expr). Those details land fixture-by-fixture.
 */
#include "k2c_lower.h"
#include "kir.h"

#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

static void
mkdir_parent(const char *path)
{
    char tmp[1024];
    size_t i;

    snprintf(tmp, sizeof(tmp), "%s", path);
    for(i = 1; i < strlen(tmp); i++) {
        if(tmp[i] == '/') {
            tmp[i] = '\0';
            mkdir(tmp, 0755);
            tmp[i] = '/';
        }
    }
}

/* Strip .kry extension from a relative path. */
static void
stem_from_source(const char *src, char *dst, size_t dst_size)
{
    size_t n = strlen(src);

    if(n > 4 && strcmp(src + n - 4, ".kry") == 0)
        n -= 4;
    if(n >= dst_size)
        n = dst_size - 1;
    memcpy(dst, src, n);
    dst[n] = '\0';
}

/* Build a C header guard from a relative path. */
static void
guard_from_stem(const char *stem, char *dst, size_t dst_size)
{
    size_t n = 0;

    if(dst_size > 2) {
        dst[n++] = 'K';
        dst[n++] = '_';
    }
    for(const char *p = stem; *p && n + 1 < dst_size; p++) {
        char c = *p;

        if(isalnum((unsigned char)c))
            dst[n++] = isalpha((unsigned char)c) ? (char)toupper(c) : c;
        else
            dst[n++] = '_';
    }
    dst[n] = '\0';
}

/* Emit a single .h + .c pair for one KirModule. */
static void
lower_module(const KirModule *m, const char *out_dir)
{
    char stem[512];
    char guard[600];
    char hpath[1024];
    char cpath[1024];
    FILE *h;
    FILE *c;
    int i;

    stem_from_source(m->source_path, stem, sizeof(stem));
    guard_from_stem(stem, guard, sizeof(guard));
    snprintf(hpath, sizeof(hpath), "%s/%s.h", out_dir, stem);
    snprintf(cpath, sizeof(cpath), "%s/%s.c", out_dir, stem);
    mkdir_parent(hpath);

    /* --- header --- */
    h = fopen(hpath, "wb");
    if(h == NULL)
        return;
    fprintf(h, "/* Generated by k2c from %s. */\n", m->source_path);
    fprintf(h, "#ifndef %s\n#define %s\n\n", guard, guard);
    for(i = 0; i < m->import_count; i++) {
        const KirImport *imp = &m->imports[i];

        if(imp->kind == KIR_IMPORT_HEADER)
            fprintf(h, "#include \"%s\"\n", imp->target);
    }
    for(i = 0; i < m->function_count; i++) {
        const KirFunction *fn = &m->functions[i];

        if(fn->exported)
            fprintf(h, "void %s(void);\n", fn->name);
    }
    fprintf(h, "\n#endif /* %s */\n", guard);
    fclose(h);

    /* --- source --- */
    c = fopen(cpath, "wb");
    if(c == NULL)
        return;
    fprintf(c, "/* Generated by k2c from %s. */\n", m->source_path);
    fprintf(c, "#include \"%s.h\"\n", stem);
    fprintf(c, "#include <stdio.h>\n\n");
    for(i = 0; i < m->function_count; i++) {
        const KirFunction *fn = &m->functions[i];
        int j;

        fprintf(c, "\nvoid\n%s(void)\n{\n", fn->name);
        for(j = 0; j < fn->stmt_count; j++) {
            const KirStmt *st = &fn->stmts[j];
            const char *t = st->text;

            if(st->kind == KIR_STMT_BLOCK_CLOSE) {
                fprintf(c, "}\n");
            } else if(t[0] != '\0') {
                /* Append ';' if the line doesn't end with '{' or ';' */
                size_t len = strlen(t);
                const char *semi = "";

                if(len > 0 && t[len - 1] != '{' && t[len - 1] != ';' &&
                   t[len - 1] != ':')
                    semi = ";";
                fprintf(c, "    %s%s\n", t, semi);
            }
        }
        fprintf(c, "}\n");
    }
    fclose(c);
}

void
k2c_lower(const KirProgram *program, const char *root, const char *out_dir)
{
    int i;

    if(program == NULL)
        return;
    for(i = 0; i < program->module_count; i++)
        lower_module(&program->modules[i], out_dir);
}
