#!/bin/sh
# Write a C source holding each runtime header's text, so zi2c and zi2cpp
# can copy the headers a program includes next to its generated code.
set -eu
echo '/* Generated by scripts/embed_headers.sh. Do not edit. */'
echo '#include "zir_runtime.h"'
echo '#include <stddef.h>'
echo 'const ZirRuntimeHeader ZirRuntimeHeaders[] = {'
for header in "$@"; do
    printf '    {"%s",\n' "$(basename "$header")"
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/     "/' -e 's/$/\\n"/' "$header"
    echo '    },'
done
echo '    {NULL, NULL}'
echo '};'
