#!/bin/sh
set -eu

bin_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

usage()
{
    echo 'usage: ziran check|ir|build|bundle|run|fmt [options] file.zi|file.zir ...' >&2
    exit 2
}

test "$#" -gt 0 || usage
command=$1
shift
case "$command" in
    check) exec "$bin_dir/zi2zir" --check-only "$@" ;;
    ir) exec "$bin_dir/zi2zir" "$@" ;;
    fmt) exec "$bin_dir/zi-fmt" "$@" ;;
    bundle) exec "$bin_dir/zi2zib" bundle "$@" ;;
    run) exec "$bin_dir/zi2zib" run "$@" ;;
    build)
        test "$#" -gt 0 || usage
        case "$1" in
            --target=c) shift; exec "$bin_dir/zi2c" --no-main "$@" ;;
            --target=go) shift; exec "$bin_dir/zi2go" --no-main "$@" ;;
            --target=cpp) shift; exec "$bin_dir/zi2cpp" --no-main "$@" ;;
            *) usage ;;
        esac
        ;;
    *) usage ;;
esac
