/* Generated by zi2c from compiler_expression.zi. */
#ifndef ZIRAN_COMPILER_EXPRESSION_H
#define ZIRAN_COMPILER_EXPRESSION_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_string.h"
#include "compiler_scan.h"
#include "compiler_source.h"
#include "compiler_text.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct ExpressionHooks ExpressionHooks;
typedef int32_t StatementExpressionError;
typedef struct StatementExpression StatementExpression;
typedef struct ExpressionBegin {
    void *context;
    int64_t (*call)(void *);
} ExpressionBegin;
typedef struct ExpressionToken {
    void *context;
    String (*call)(void *);
} ExpressionToken;
typedef struct ExpressionPrefix {
    void *context;
    int32_t (*call)(void *);
} ExpressionPrefix;
typedef struct ExpressionAdvance {
    void *context;
    void (*call)(void *);
} ExpressionAdvance;
typedef struct ExpressionBinary {
    void *context;
    int32_t (*call)(void *, int64_t, String, int32_t, int32_t);
} ExpressionBinary;
typedef struct ExpressionConditionalError {
    void *context;
    void (*call)(void *);
} ExpressionConditionalError;

struct ExpressionHooks {
    int32_t* depth;
    int32_t* failed;
    ExpressionBegin begin;
    ExpressionToken token;
    ExpressionPrefix prefix;
    ExpressionAdvance advance;
    ExpressionBinary binary;
    ExpressionConditionalError conditional_error;
};

enum {
    StatementExpressionError_None = 0,
    StatementExpressionError_Modifier = 1,
    StatementExpressionError_ArrayLiteral = 2,
};

struct StatementExpression {
    String name;
    String type;
    String value;
    String lhs;
    String assignment;
    String modifier;
    bool has_declaration;
    bool has_value;
    bool is_else;
    StatementExpressionError error;
};
int32_t compiler_expression_BinaryPrecedence(String operator);
String compiler_expression_BinarySpelling(String operator);
int32_t compiler_expression_ParseBinary(ExpressionHooks* hooks, int32_t minimum);
int32_t compiler_expression_CharacterByte(String literal);
StatementExpression compiler_expression_StatementParts(String source, StatementKind kind);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_EXPRESSION_H */
