/* Generated by zi2c from compiler_expression.zi. */
#include "compiler_expression.h"
static int32_t compiler_expression_Hex(uint8_t byte);
static String compiler_expression_Trim(String source);
static String compiler_expression_SkipSpace(String source);
static int64_t compiler_expression_FindByte(String source, uint8_t wanted);
static int64_t compiler_expression_FindPair(String source, String wanted);
static bool compiler_expression_WordAt(String source, int64_t at, String word);
static bool compiler_expression_AssignmentOperator(String operator);

int32_t
compiler_expression_BinaryPrecedence(String operator)
{
    if (StringEqual(operator, StringLiteral("||"))) {
        return 2;
    }
    if (StringEqual(operator, StringLiteral("&&"))) {
        return 3;
    }
    if (StringEqual(operator, StringLiteral("|"))) {
        return 4;
    }
    if (StringEqual(operator, StringLiteral("^"))) {
        return 5;
    }
    if (StringEqual(operator, StringLiteral("&"))) {
        return 6;
    }
    if (StringEqual(operator, StringLiteral("==")) || StringEqual(operator, StringLiteral("!="))) {
        return 7;
    }
    bool value_0 = StringEqual(operator, StringLiteral("<")) || StringEqual(operator, StringLiteral("<=")) || StringEqual(operator, StringLiteral(">"));
    if (value_0 || StringEqual(operator, StringLiteral(">="))) {
        return 8;
    }
    if (StringEqual(operator, StringLiteral("<<")) || StringEqual(operator, StringLiteral(">>"))) {
        return 9;
    }
    if (StringEqual(operator, StringLiteral("+")) || StringEqual(operator, StringLiteral("-"))) {
        return 10;
    }
    bool value_1 = StringEqual(operator, StringLiteral("*")) || StringEqual(operator, StringLiteral("/")) || StringEqual(operator, StringLiteral("%"));
    if (value_1) {
        return 11;
    }
    return 0;
}

String
compiler_expression_BinarySpelling(String operator)
{
    String operators[18] = {StringLiteral("||"), StringLiteral("&&"), StringLiteral("|"), StringLiteral("^"), StringLiteral("&"), StringLiteral("=="), StringLiteral("!="), StringLiteral("<"), StringLiteral("<="), StringLiteral(">"), StringLiteral(">="), StringLiteral("<<"), StringLiteral(">>"), StringLiteral("+"), StringLiteral("-"), StringLiteral("*"), StringLiteral("/"), StringLiteral("%")};
    for (int64_t it_index = 0LL; it_index < 18; it_index++) {
        String spelling = ZIRAN_INDEX(operators, 18, it_index);
        if (StringEqual(operator, spelling)) {
            return spelling;
        }
    }
    return StringLiteral("");
}

int32_t
compiler_expression_ParseBinary(ExpressionHooks* hooks, int32_t minimum)
{
    ExpressionBegin begin = hooks->begin;
    ExpressionToken token = hooks->token;
    ExpressionPrefix prefix = hooks->prefix;
    ExpressionAdvance advance = hooks->advance;
    ExpressionBinary binary = hooks->binary;
    ExpressionConditionalError conditional_error = hooks->conditional_error;
    ExpressionBegin value_0 = begin;
    int64_t start = value_0.call(value_0.context);
    ExpressionPrefix value_1 = prefix;
    int32_t left = value_1.call(value_1.context);
    (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) + 1u);
    if (*(hooks->depth) > 128) {
        (*(hooks->failed)) = 1;
        (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) - 1u);
        return -1;
    }
    while (*(hooks->failed) == 0) {
        ExpressionToken value_2 = token;
        String operator = compiler_expression_BinarySpelling(value_2.call(value_2.context));
        int32_t precedence = compiler_expression_BinaryPrecedence(operator);
        if (precedence == 0 || precedence < minimum) {
            break;
        }
        ExpressionAdvance value_3 = advance;
        value_3.call(value_3.context);
        int32_t right = compiler_expression_ParseBinary(hooks, (int32_t)((uint32_t)precedence + 1u));
        ExpressionBinary value_4 = binary;
        left = value_4.call(value_4.context, start, operator, left, right);
    }
    ExpressionToken value_5 = token;
    if (StringEqual(value_5.call(value_5.context), StringLiteral("\?"))) {
        ExpressionConditionalError value_6 = conditional_error;
        value_6.call(value_6.context);
    }
    (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) - 1u);
    return left;
}

int32_t
compiler_expression_CharacterByte(String literal)
{
    int64_t value_0 = (int64_t)(literal).length;
    bool value_1 = value_0 == 3LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2) == 34;
    if (value_1 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) < 128) {
        return (int32_t)((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1));
    }
    int64_t value_2 = (int64_t)(literal).length;
    bool value_3 = value_2 == 4LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) == 92;
    if (value_3 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 3) == 34) {
        uint8_t escape = (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2);
        if (escape == 48) {
            return 0;
        }
        if (escape == 110) {
            return 10;
        }
        if (escape == 114) {
            return 13;
        }
        if (escape == 116) {
            return 9;
        }
        if (escape == 34) {
            return 34;
        }
        if (escape == 92) {
            return 92;
        }
        return -1;
    }
    int64_t value_4 = (int64_t)(literal).length;
    bool value_5 = value_4 == 6LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) == 92;
    bool value_6 = value_5 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2) == 120 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 5) == 34;
    if (value_6) {
        int32_t high = compiler_expression_Hex((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 3));
        int32_t low = compiler_expression_Hex((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 4));
        if (high >= 0 && low >= 0) {
            return (int32_t)(((uint32_t)high * 16u) + (uint32_t)low);
        }
    }
    return -1;
}

StatementExpression
compiler_expression_StatementParts(String source, StatementKind kind)
{
    StatementExpression result = {0};
    bool value_0 = kind == ((StatementKind)(6));
    bool value_1 = value_0;
    if (value_1) {
        bool value_2 = compiler_expression_WordAt(source, 0LL, StringLiteral("else"));
        value_1 = value_2;
    }
    result.is_else = value_1;
    if (kind == ((StatementKind)(3))) {
        int64_t colon = compiler_expression_FindByte(source, 58);
        if (colon >= 0LL) {
            result.has_declaration = true;
            String value_3 = source;
            String value_4 = compiler_expression_Trim(StringRange(value_3, (int64_t)0LL, (int64_t)colon));
            result.name = value_4;
            String value_5 = source;
            String value_6 = StringRange(value_5, (int64_t)((int64_t)((uint64_t)colon + UINT64_C(1))), (int64_t)value_5.length);
            String type = value_6;
            int64_t equals = compiler_expression_FindByte(type, 61);
            if (equals >= 0LL) {
                result.has_value = true;
                String value_7 = type;
                String value_8 = StringRange(value_7, (int64_t)((int64_t)((uint64_t)equals + UINT64_C(1))), (int64_t)value_7.length);
                result.value = value_8;
                String value_9 = type;
                type = StringRange(value_9, (int64_t)0LL, (int64_t)equals);
            }
            type = compiler_expression_Trim(type);
            int64_t value_10 = (int64_t)(type).length;
            bool value_11 = value_10 > 0LL;
            if (value_11) {
                uint8_t value_12 = (uint8_t)ZIRAN_INDEX(type.data, type.length, ((int64_t)((uint64_t)((int64_t)(type).length) - UINT64_C(1))));
                value_11 = (value_12 == 59);
            }
            if (value_11) {
                String value_13 = type;
                String value_14 = StringRange(value_13, (int64_t)0LL, (int64_t)((int64_t)((uint64_t)((int64_t)(type).length) - UINT64_C(1))));
                type = compiler_expression_Trim(value_14);
            }
            result.type = type;
            int64_t modifier = compiler_expression_FindByte(type, 35);
            if (modifier >= 0LL) {
                result.error = StatementExpressionError_Modifier;
                String value_15 = type;
                result.modifier = StringRange(value_15, (int64_t)modifier, (int64_t)value_15.length);
                return result;
            }
        }
    } else if (kind == ((StatementKind)(4))) {
        int64_t at = 0LL;
        while (true) {
            int64_t value_16 = (int64_t)(source).length;
            if (!(at < value_16)) { break; }
            Scan token = compiler_scan_NextToken(source, at, 1, 1);
            if (((TokenKind)(token.kind)) == ((TokenKind)(0))) {
                break;
            }
            String value_17 = source;
            String operator = StringRange(value_17, (int64_t)token.begin, (int64_t)token.end);
            if (compiler_expression_AssignmentOperator(operator)) {
                result.assignment = operator;
                String value_18 = source;
                result.lhs = StringRange(value_18, (int64_t)0LL, (int64_t)token.begin);
                String value_19 = source;
                result.value = StringRange(value_19, (int64_t)token.end, (int64_t)value_19.length);
                result.has_value = true;
                break;
            }
            at = token.end;
        }
    } else if (kind == ((StatementKind)(10)) || kind == ((StatementKind)(14))) {
        int64_t value_20 = (int64_t)(source).length;
        if (value_20 >= 6LL) {
            String value_21 = source;
            result.value = StringRange(value_21, (int64_t)6LL, (int64_t)value_21.length);
            result.has_value = true;
        }
    } else if (kind == ((StatementKind)(5))) {
        result.value = source;
        result.has_value = true;
    } else if (kind == ((StatementKind)(16))) {
        int64_t value_22 = (int64_t)(source).length;
        if (value_22 >= 2LL) {
            String value_23 = source;
            String condition = compiler_expression_SkipSpace(StringRange(value_23, (int64_t)2LL, (int64_t)value_23.length));
            int64_t value_24 = (int64_t)(condition).length;
            bool value_25 = value_24 > 9LL;
            if (value_25) {
                String value_26 = condition;
                value_25 = (StringEqual(StringRange(value_26, (int64_t)0LL, (int64_t)9LL), StringLiteral("#complete")));
            }
            bool value_27 = value_25;
            bool value_28 = value_27;
            if (value_28) {
                bool value_29 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(condition.data, condition.length, 9));
                value_28 = value_29;
            }
            if (value_28) {
                String value_30 = condition;
                condition = compiler_expression_SkipSpace(StringRange(value_30, (int64_t)9LL, (int64_t)value_30.length));
            }
            int64_t equals = compiler_expression_FindPair(condition, StringLiteral("=="));
            if (equals >= 0LL) {
                String value_31 = condition;
                condition = compiler_expression_Trim(StringRange(value_31, (int64_t)0LL, (int64_t)equals));
            }
            result.value = condition;
            result.has_value = true;
        }
    } else if (kind == ((StatementKind)(7)) || kind == ((StatementKind)(6))) {
        String value_32 = source;
        int64_t value_33 = compiler_text_BlockHeaderEnd(source);
        String condition = StringRange(value_32, (int64_t)0LL, (int64_t)value_33);
        int64_t value_34 = (int64_t)(condition).length;
        bool value_35 = value_34 >= 4LL;
        if (value_35) {
            String value_36 = condition;
            value_35 = (StringEqual(StringRange(value_36, (int64_t)0LL, (int64_t)4LL), StringLiteral("else")));
        }
        if (value_35) {
            String value_37 = condition;
            condition = compiler_expression_SkipSpace(StringRange(value_37, (int64_t)4LL, (int64_t)value_37.length));
        }
        int64_t at = 0LL;
        while (true) {
            int64_t value_38 = (int64_t)(condition).length;
            bool value_39 = at < value_38;
            bool value_40 = value_39;
            if (value_40) {
                bool value_41 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(condition.data, condition.length, at));
                value_40 = !value_41;
            }
            if (!(value_40 && (uint8_t)ZIRAN_INDEX(condition.data, condition.length, at) != 40)) { break; }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        String value_42 = condition;
        result.value = StringRange(value_42, (int64_t)at, (int64_t)value_42.length);
        result.has_value = true;
    }
    bool value_43 = result.has_value;
    bool value_44 = value_43;
    if (value_44) {
        bool value_45 = StringEqual(compiler_expression_SkipSpace(result.value), StringLiteral(";"));
        value_44 = value_45;
    }
    if (value_44) {
        result.has_value = false;
    }
    bool value_46 = result.has_value && kind == ((StatementKind)(3));
    if (value_46) {
        int64_t value_47 = (int64_t)(result.type).length;
        value_46 = (value_47 > 0LL);
    }
    if (value_46 && (uint8_t)ZIRAN_INDEX(result.type.data, result.type.length, 0) == 91) {
        String value = compiler_expression_SkipSpace(result.value);
        int64_t value_48 = (int64_t)(value).length;
        if (value_48 > 0LL && (uint8_t)ZIRAN_INDEX(value.data, value.length, 0) == 123) {
            result.error = StatementExpressionError_ArrayLiteral;
        }
    }
    return result;
}

static int32_t
compiler_expression_Hex(uint8_t byte)
{
    if (byte >= 48 && byte <= 57) {
        return (int32_t)(((uint8_t)((uint32_t)byte - 48u)));
    }
    if (byte >= 65 && byte <= 70) {
        return (int32_t)((uint32_t)(((uint8_t)((uint32_t)byte - 65u))) + 10u);
    }
    if (byte >= 97 && byte <= 102) {
        return (int32_t)((uint32_t)(((uint8_t)((uint32_t)byte - 97u))) + 10u);
    }
    return -1;
}

static String
compiler_expression_Trim(String source)
{
    SourceRange range = compiler_text_TrimRange(source);
    String value_0 = source;
    return StringRange(value_0, (int64_t)range.begin, (int64_t)range.end);
}

static String
compiler_expression_SkipSpace(String source)
{
    String value_0 = source;
    SourceRange value_1 = compiler_text_TrimRange(source);
    return StringRange(value_0, (int64_t)value_1.begin, (int64_t)value_0.length);
}

static int64_t
compiler_expression_FindByte(String source, uint8_t wanted)
{
    {
        int64_t range_first_0 = 0LL;
        int64_t range_last_0 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1));
        int64_t at = range_first_0;
        while (at <= range_last_0) {
            if ((uint8_t)ZIRAN_INDEX(source.data, source.length, at) == wanted) {
                return at;
            }
            if (at == range_last_0) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

static int64_t
compiler_expression_FindPair(String source, String wanted)
{
    {
        int64_t range_first_0 = 0LL;
        int64_t range_last_0 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(2));
        int64_t at = range_first_0;
        while (at <= range_last_0) {
            String value_0 = source;
            bool value_1 = StringEqual(StringRange(value_0, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + UINT64_C(2)))), wanted);
            if (value_1) {
                return at;
            }
            if (at == range_last_0) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

static bool
compiler_expression_WordAt(String source, int64_t at, String word)
{
    bool value_0 = at >= 0LL;
    if (value_0) {
        int64_t value_1 = (int64_t)(word).length;
        int64_t value_2 = (int64_t)((uint64_t)((int64_t)(source).length) - (uint64_t)at);
        value_0 = (value_1 <= value_2);
    }
    bool value_3 = value_0;
    if (value_3) {
        String value_4 = source;
        String value_5 = StringRange(value_4, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length))));
        value_3 = (StringEqual(value_5, word));
    }
    bool value_6 = value_3;
    bool value_7 = value_6;
    if (value_7) {
        int64_t value_8 = (int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length));
        int64_t value_9 = (int64_t)(source).length;
        bool value_10 = value_8 == value_9;
        bool value_11 = value_10;
        if (!value_11) {
            uint8_t value_12 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length))));
            bool value_13 = compiler_text_SpaceByte(value_12);
            value_11 = value_13;
        }
        value_7 = value_11;
    }
    return value_7;
}

static bool
compiler_expression_AssignmentOperator(String operator)
{
    bool value_0 = StringEqual(operator, StringLiteral("=")) || StringEqual(operator, StringLiteral("+=")) || StringEqual(operator, StringLiteral("-="));
    bool value_1 = value_0 || StringEqual(operator, StringLiteral("*=")) || StringEqual(operator, StringLiteral("/="));
    bool value_2 = value_1 || StringEqual(operator, StringLiteral("%=")) || StringEqual(operator, StringLiteral("&="));
    bool value_3 = value_2 || StringEqual(operator, StringLiteral("|=")) || StringEqual(operator, StringLiteral("^="));
    bool value_4 = value_3 || StringEqual(operator, StringLiteral("<<=")) || StringEqual(operator, StringLiteral(">>="));
    return value_4;
}
