/* Generated by zi2c from compiler_scan.zi. */
#ifndef ZIRAN_COMPILER_SCAN_H
#define ZIRAN_COMPILER_SCAN_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_string.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef int32_t TokenKind;
typedef struct Scan Scan;
#ifdef ZIRAN_COMPILER_SCAN_H_PRIVATE
typedef struct Cursor Cursor;
#endif

enum {
    TokenKind_Eof = 0,
    TokenKind_Ident = 1,
    TokenKind_Int = 2,
    TokenKind_Float = 3,
    TokenKind_String = 4,
    TokenKind_Char = 5,
    TokenKind_Directive = 6,
    TokenKind_Operator = 7,
    TokenKind_Punct = 8,
    TokenKind_Unknown = 9,
};

struct Scan {
    TokenKind kind;
    int64_t begin;
    int64_t end;
    int32_t line;
    int32_t column;
    int32_t after_line;
    int32_t after_column;
};
#ifdef ZIRAN_COMPILER_SCAN_H_PRIVATE

struct Cursor {
    int64_t at;
    int32_t line;
    int32_t column;
};
#endif
Scan compiler_scan_NextToken(String source, int64_t at, int32_t line, int32_t column);
String compiler_scan_KindName(TokenKind kind);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_SCAN_H */
