/* Generated by zi2c from compiler_scan.zi. */
#define ZIRAN_COMPILER_SCAN_H_PRIVATE 1
#include "compiler_scan.h"
#undef ZIRAN_COMPILER_SCAN_H_PRIVATE
static uint8_t compiler_scan_Byte(String source, int64_t at);
static bool compiler_scan_Space(uint8_t byte);
static bool compiler_scan_Digit(uint8_t byte);
static bool compiler_scan_Letter(uint8_t byte);
static bool compiler_scan_Identifier(uint8_t byte);
static void compiler_scan_Advance(Cursor* cursor, String source);
static bool compiler_scan_Contains(String bytes, uint8_t byte);
static bool compiler_scan_Exponent(uint8_t byte, bool hexadecimal);
static int64_t compiler_scan_OperatorLength(String source, int64_t at);

static uint8_t
compiler_scan_Byte(String source, int64_t at)
{
    bool value_0 = at < 0LL;
    if (!value_0) {
        int64_t value_1 = (int64_t)(source).length;
        value_0 = (at >= value_1);
    }
    if (value_0) {
        return 0;
    }
    return (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
}

static bool
compiler_scan_Space(uint8_t byte)
{
    return byte == 32 || (byte >= 9 && byte <= 13);
}

static bool
compiler_scan_Digit(uint8_t byte)
{
    return byte >= 48 && byte <= 57;
}

static bool
compiler_scan_Letter(uint8_t byte)
{
    return (byte >= 65 && byte <= 90) || (byte >= 97 && byte <= 122) || byte == 95;
}

static bool
compiler_scan_Identifier(uint8_t byte)
{
    bool value_0 = compiler_scan_Letter(byte);
    bool value_1 = value_0;
    if (!value_1) {
        bool value_2 = compiler_scan_Digit(byte);
        value_1 = value_2;
    }
    return value_1;
}

static void
compiler_scan_Advance(Cursor* cursor, String source)
{
    if (compiler_scan_Byte(source, cursor->at) == 10) {
        cursor->line = (int32_t)((uint32_t)(cursor->line) + 1u);
        cursor->column = 1;
    } else {
        cursor->column = (int32_t)((uint32_t)(cursor->column) + 1u);
    }
    cursor->at = (int64_t)((uint64_t)(cursor->at) + UINT64_C(1));
}

static bool
compiler_scan_Contains(String bytes, uint8_t byte)
{
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_0 = (int64_t)(bytes).length;
            if (!(it_index < value_0)) { break; }
            uint8_t value = (uint8_t)ZIRAN_INDEX(bytes.data, bytes.length, it_index);
            if (value == byte) {
                return true;
            }
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
    return false;
}

static bool
compiler_scan_Exponent(uint8_t byte, bool hexadecimal)
{
    if (hexadecimal) {
        return byte == 112 || byte == 80;
    }
    return byte == 101 || byte == 69;
}

static int64_t
compiler_scan_OperatorLength(String source, int64_t at)
{
    uint8_t first = compiler_scan_Byte(source, at);
    uint8_t second = compiler_scan_Byte(source, (int64_t)((uint64_t)at + UINT64_C(1)));
    if ((first == 60 || first == 62) && second == first) {
        if (compiler_scan_Byte(source, (int64_t)((uint64_t)at + UINT64_C(2))) == 61) {
            return 3LL;
        }
        return 2LL;
    }
    bool value_0 = (first == 58 && (second == 58 || second == 61)) || (first == 43 && second == 43) || (first == 45 && (second == 45 || second == 62));
    bool value_1 = value_0 || (first == 61 && (second == 62 || second == 61));
    if (!value_1) {
        bool value_2 = compiler_scan_Contains(StringLiteral("!<>+-*/%&|^"), first);
        value_1 = (value_2 && second == 61);
    }
    if (value_1 || (first == 38 && second == 38) || (first == 124 && second == 124)) {
        return 2LL;
    }
    if (compiler_scan_Contains(StringLiteral("+-*/%=!<>.&|^\?~"), first)) {
        return 1LL;
    }
    return 0LL;
}

Scan
compiler_scan_NextToken(String source, int64_t at, int32_t line, int32_t column)
{
    Cursor cursor = {.at = at, .line = line, .column = column};
    while (compiler_scan_Space(compiler_scan_Byte(source, cursor.at))) {
        compiler_scan_Advance(&(cursor), source);
    }
    Scan token = {0};
    token.begin = cursor.at;
    token.line = cursor.line;
    token.column = cursor.column;
    uint8_t byte = compiler_scan_Byte(source, cursor.at);
    if (byte == 0) {
        token.kind = TokenKind_Eof;
    } else {
        bool value_0 = byte == 35;
        if (!value_0) {
            bool value_1 = compiler_scan_Letter(byte);
            value_0 = value_1;
        }
        if (value_0) {
            token.kind = TokenKind_Ident;
            if (byte == 35) {
                token.kind = TokenKind_Directive;
            }
            compiler_scan_Advance(&(cursor), source);
            while (compiler_scan_Identifier(compiler_scan_Byte(source, cursor.at))) {
                compiler_scan_Advance(&(cursor), source);
            }
        } else {
            bool value_2 = compiler_scan_Digit(byte);
            bool value_3 = value_2;
            if (!value_3) {
                bool value_4 = byte == 46;
                if (value_4) {
                    bool value_5 = compiler_scan_Digit(compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) + UINT64_C(1))));
                    value_4 = value_5;
                }
                value_3 = value_4;
            }
            if (value_3) {
                bool real = byte == 46;
                bool value_6 = byte == 48;
                if (value_6) {
                    bool value_7 = compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) + UINT64_C(1))) == 120;
                    bool value_8 = value_7;
                    if (!value_8) {
                        bool value_9 = compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) + UINT64_C(1))) == 88;
                        value_8 = value_9;
                    }
                    value_6 = value_8;
                }
                bool hexadecimal = value_6;
                compiler_scan_Advance(&(cursor), source);
                while (true) {
                    uint8_t current = compiler_scan_Byte(source, cursor.at);
                    bool value_10 = compiler_scan_Identifier(current);
                    bool value_11 = !value_10 && current != 46;
                    if (value_11) {
                        bool value_12 = current == 43 || current == 45;
                        if (value_12) {
                            bool value_13 = compiler_scan_Exponent(compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) - UINT64_C(1))), hexadecimal);
                            value_12 = value_13;
                        }
                        value_11 = !value_12;
                    }
                    if (value_11) {
                        break;
                    }
                    bool value_14 = current == 46;
                    if (!value_14) {
                        bool value_15 = compiler_scan_Exponent(current, hexadecimal);
                        value_14 = value_15;
                    }
                    if (value_14) {
                        real = true;
                    }
                    compiler_scan_Advance(&(cursor), source);
                }
                token.kind = TokenKind_Int;
                if (real) {
                    token.kind = TokenKind_Float;
                }
            } else if (byte == 34 || byte == 39) {
                token.kind = TokenKind_String;
                if (byte == 39) {
                    token.kind = TokenKind_Char;
                }
                compiler_scan_Advance(&(cursor), source);
                while (compiler_scan_Byte(source, cursor.at) != 0) {
                    uint8_t current = compiler_scan_Byte(source, cursor.at);
                    compiler_scan_Advance(&(cursor), source);
                    bool value_16 = current == 92;
                    if (value_16) {
                        bool value_17 = compiler_scan_Byte(source, cursor.at) != 0;
                        value_16 = value_17;
                    }
                    if (value_16) {
                        compiler_scan_Advance(&(cursor), source);
                    } else if (current == byte) {
                        break;
                    }
                }
            } else {
                bool value_18 = compiler_scan_Contains(StringLiteral("{}()[],;"), byte);
                bool value_19 = value_18;
                if (!value_19) {
                    bool value_20 = byte == 58;
                    if (value_20) {
                        bool value_21 = compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) + UINT64_C(1))) != 58;
                        value_20 = value_21;
                    }
                    bool value_22 = value_20;
                    if (value_22) {
                        bool value_23 = compiler_scan_Byte(source, (int64_t)((uint64_t)(cursor.at) + UINT64_C(1))) != 61;
                        value_22 = value_23;
                    }
                    value_19 = value_22;
                }
                if (value_19) {
                    token.kind = TokenKind_Punct;
                    compiler_scan_Advance(&(cursor), source);
                } else {
                    int64_t length = compiler_scan_OperatorLength(source, cursor.at);
                    token.kind = TokenKind_Operator;
                    if (length == 0LL) {
                        token.kind = TokenKind_Unknown;
                        length = 1LL;
                    }
                    int64_t index = 0LL;
                    while (index < length) {
                        compiler_scan_Advance(&(cursor), source);
                        index = (int64_t)((uint64_t)index + UINT64_C(1));
                    }
                }
            }
        }
    }
    token.end = cursor.at;
    token.after_line = cursor.line;
    token.after_column = cursor.column;
    return token;
}

String
compiler_scan_KindName(TokenKind kind)
{
    if (kind == TokenKind_Eof) {
        return StringLiteral("eof");
    }
    if (kind == TokenKind_Ident) {
        return StringLiteral("ident");
    }
    if (kind == TokenKind_Int) {
        return StringLiteral("int");
    }
    if (kind == TokenKind_Float) {
        return StringLiteral("float");
    }
    if (kind == TokenKind_String) {
        return StringLiteral("string");
    }
    if (kind == TokenKind_Char) {
        return StringLiteral("char");
    }
    if (kind == TokenKind_Directive) {
        return StringLiteral("directive");
    }
    if (kind == TokenKind_Operator) {
        return StringLiteral("operator");
    }
    if (kind == TokenKind_Punct) {
        return StringLiteral("punct");
    }
    return StringLiteral("unknown");
}
