/* Generated by zi2c from compiler_declaration.zi. */
#ifndef ZIRAN_COMPILER_DECLARATION_H
#define ZIRAN_COMPILER_DECLARATION_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_slice.h"
#include "zir_string.h"
#include "compiler_text.h"
#include "compiler_source.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef int32_t DeclarationError;
typedef struct ExportDirective ExportDirective;
typedef struct ParameterRewrite ParameterRewrite;
typedef int32_t ImportMode;
typedef struct ModuleImport ModuleImport;
typedef struct LibraryDeclaration LibraryDeclaration;
typedef struct MethodSymbol MethodSymbol;
#ifdef ZIRAN_COMPILER_DECLARATION_H_PRIVATE
typedef struct QuotedText QuotedText;
#endif

enum {
    DeclarationError_None = 0,
    DeclarationError_ExportQuote = 1,
    DeclarationError_ExportName = 2,
    DeclarationError_Parameters = 3,
    DeclarationError_DefaultValue = 4,
    DeclarationError_UsingModifier = 5,
    DeclarationError_UsingType = 6,
    DeclarationError_UsingName = 7,
    DeclarationError_ImportQuote = 8,
    DeclarationError_ImportCharacter = 9,
    DeclarationError_ImportMode = 10,
    DeclarationError_ImportDirSyntax = 11,
    DeclarationError_ImportDirPath = 12,
    DeclarationError_ImportDirName = 13,
    DeclarationError_ImportFileSyntax = 14,
    DeclarationError_ImportFilePath = 15,
    DeclarationError_ImportFileName = 16,
    DeclarationError_ImportAlias = 17,
    DeclarationError_ImportTarget = 18,
    DeclarationError_ImportPackage = 19,
    DeclarationError_ImportUsing = 20,
    DeclarationError_LibraryQuote = 21,
    DeclarationError_LibraryEnd = 22,
    DeclarationError_LibraryCharacter = 23,
};

struct ExportDirective {
    DeclarationError error;
    int32_t kind;
    String symbol;
    String body;
};

struct ParameterRewrite {
    DeclarationError error;
    int64_t count;
    int32_t parameters;
    bool has_defaults;
    uint64_t using_parameters;
};

enum {
    ImportMode_Module = 0,
    ImportMode_File = 1,
    ImportMode_Directory = 2,
};

struct ModuleImport {
    DeclarationError error;
    bool present;
    bool named;
    bool using_import;
    ImportMode mode;
    String name;
    String target;
    String path;
    String detail;
};

struct LibraryDeclaration {
    DeclarationError error;
    bool present;
    String name;
    String target;
};

struct MethodSymbol {
    bool valid;
    String receiver;
    String method;
};
#ifdef ZIRAN_COMPILER_DECLARATION_H_PRIVATE

struct QuotedText {
    bool valid;
    String value;
    int64_t end;
};
#endif
String compiler_declaration_ErrorText(DeclarationError error);
ExportDirective compiler_declaration_ProgramExport(String source, int64_t symbol_limit);
ParameterRewrite compiler_declaration_RewriteParameters(String source, Slice output, bool strip_defaults, bool strip_using, int64_t name_limit);
ModuleImport compiler_declaration_ImportDeclaration(String source, int64_t name_limit, int64_t path_limit);
LibraryDeclaration compiler_declaration_SystemLibrary(String source, int64_t name_limit, int64_t path_limit);
MethodSymbol compiler_declaration_ForeignMethod(String source, int64_t receiver_limit, int64_t method_limit, bool python);
bool compiler_declaration_PythonAttribute(String source, int64_t name_limit);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_DECLARATION_H */
