/* Generated by zi2c from compiler_declaration.zi. */
#define ZIRAN_COMPILER_DECLARATION_H_PRIVATE 1
#include "compiler_declaration.h"
#undef ZIRAN_COMPILER_DECLARATION_H_PRIVATE
#include <stdint.h>
#include <stdlib.h>

/* SignedBits reads the low w bits of x as a signed number. */
static inline int64_t SignedBits(uint64_t x, int w) {
    uint64_t mask = w == 64 ? UINT64_MAX : (UINT64_C(1) << w) - 1;
    x &= mask;
    return x <= (mask >> 1) ? (int64_t)x : -1 - (int64_t)(mask - x);
}

/* IntegerOp applies op to the low w bits of a and b: 0 convert, 1 add,
 * 2 subtract, 3 multiply, 4 divide, 5 remainder, 6 shift left,
 * 7 shift right, 8 and, 9 or, 10 xor. Division by zero and
 * out-of-range shifts abort. */
static inline uint64_t IntegerOp(uint64_t a, uint64_t b, int w, int sign, int op) {
    uint64_t mask = w == 64 ? UINT64_MAX : (UINT64_C(1) << w) - 1;
    uint64_t shift = b;
    a &= mask;
    b &= mask;
    switch(op) {
    case 0: return a;
    case 1: return (a + b) & mask;
    case 2: return (a - b) & mask;
    case 3: return (a * b) & mask;
    case 4: case 5:
        if(!b) abort();
        if(sign) {
            int64_t x = SignedBits(a, w), y = SignedBits(b, w);
            if(x == INT64_MIN && y == -1) return op == 4 ? a : 0;
            return (uint64_t)(op == 4 ? x / y : x % y) & mask;
        }
        return op == 4 ? a / b : a % b;
    case 6: case 7:
        if(shift >= (uint64_t)w) abort();
        if(op == 6) return (a << shift) & mask;
        if(!shift) return a;
        return (a >> shift) |
            ((sign && (a & (UINT64_C(1) << (w - 1)))) ? mask ^ (mask >> shift) : 0);
    case 8: return a & b;
    case 9: return a | b;
    case 10: return a ^ b;
    default: abort();
    }
    return 0;
}
static int64_t compiler_declaration_Find(String source, String needle);
static String compiler_declaration_Trim(String source);
static void compiler_declaration_Put(Slice output, int64_t* used, String source);
static QuotedText compiler_declaration_Quoted(String source, int64_t limit);
static String compiler_declaration_SymbolBeforeColons(String source, int64_t limit);
static String compiler_declaration_Basename(String source);
static QuotedText compiler_declaration_UsingQuoted(String source, int64_t limit);

static int64_t
compiler_declaration_Find(String source, String needle)
{
    {
        int64_t range_first_0 = 0LL;
        int64_t range_last_0 = (int64_t)(source).length;
        int64_t at = range_first_0;
        while (at <= range_last_0) {
            int64_t value_0 = (int64_t)(needle).length;
            int64_t value_1 = (int64_t)((uint64_t)((int64_t)(source).length) - (uint64_t)at);
            bool value_2 = value_0 <= value_1;
            if (value_2) {
                String value_3 = source;
                String value_4 = StringRange(value_3, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)((int64_t)(needle).length))));
                value_2 = (StringEqual(value_4, needle));
            }
            if (value_2) {
                return at;
            }
            if (at == range_last_0) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

static String
compiler_declaration_Trim(String source)
{
    SourceRange range = compiler_text_TrimRange(source);
    String value_0 = source;
    return StringRange(value_0, (int64_t)range.begin, (int64_t)range.end);
}

static void
compiler_declaration_Put(Slice output, int64_t* used, String source)
{
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_0 = (int64_t)(source).length;
            if (!(it_index < value_0)) { break; }
            uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, it_index);
            int64_t value_1 = *(used);
            int64_t value_2 = (int64_t)(output).length;
            if (value_1 < value_2) {
                ((uint8_t *)output.data)[SliceIndex(output, (int64_t)*(used))] = byte;
            }
            (*(used)) = (int64_t)((uint64_t)((*(used))) + UINT64_C(1));
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
}

static QuotedText
compiler_declaration_Quoted(String source, int64_t limit)
{
    int64_t begin = compiler_declaration_Find(source, StringLiteral("\""));
    if (begin < 0LL) {
        return (QuotedText){0};
    }
    String value_0 = source;
    String value_1 = StringRange(value_0, (int64_t)((int64_t)((uint64_t)begin + UINT64_C(1))), (int64_t)value_0.length);
    int64_t end = compiler_declaration_Find(value_1, StringLiteral("\""));
    if (end < 0LL || end >= limit) {
        return (QuotedText){0};
    }
    end = (int64_t)((uint64_t)end + ((uint64_t)begin + UINT64_C(1)));
    String value_2 = source;
    return (QuotedText){.valid = true, .value = StringRange(value_2, (int64_t)((int64_t)((uint64_t)begin + UINT64_C(1))), (int64_t)end), .end = (int64_t)((uint64_t)end + UINT64_C(1))};
}

static String
compiler_declaration_SymbolBeforeColons(String source, int64_t limit)
{
    int64_t colons = compiler_declaration_Find(source, StringLiteral("::"));
    if (colons < 0LL) {
        return StringLiteral("");
    }
    int64_t begin = compiler_text_SkipSpace(source, 0LL, true);
    int64_t end = begin;
    while (true) {
        bool value_0 = end < colons;
        bool value_1 = value_0;
        if (value_1) {
            bool value_2 = compiler_text_IdentifierByte((uint8_t)ZIRAN_INDEX(source.data, source.length, end));
            value_1 = value_2;
        }
        if (!value_1) { break; }
        end = (int64_t)((uint64_t)end + UINT64_C(1));
    }
    bool value_3 = end == begin;
    if (!value_3) {
        int64_t value_4 = (int64_t)((uint64_t)end - (uint64_t)begin);
        value_3 = (value_4 >= limit);
    }
    bool value_5 = value_3;
    bool value_6 = value_5;
    if (!value_6) {
        int64_t value_7 = compiler_text_SkipSpace(source, end, true);
        value_6 = (value_7 != colons);
    }
    if (value_6) {
        return StringLiteral("");
    }
    String value_8 = source;
    return StringRange(value_8, (int64_t)begin, (int64_t)end);
}

static String
compiler_declaration_Basename(String source)
{
    int64_t begin = 0LL;
    {
        int64_t range_first_1 = 0LL;
        int64_t range_last_1 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1));
        int64_t at = range_first_1;
        while (at <= range_last_1) {
            if ((uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 47) {
                begin = (int64_t)((uint64_t)at + UINT64_C(1));
            }
            if (at == range_last_1) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    String value_0 = source;
    return StringRange(value_0, (int64_t)begin, (int64_t)value_0.length);
}

String
compiler_declaration_ErrorText(DeclarationError error)
{
    if (error == DeclarationError_ExportQuote) {
        return StringLiteral("#program_export requires a valid quoted symbol");
    }
    if (error == DeclarationError_ExportName) {
        return StringLiteral("#program_export symbol must be an identifier");
    }
    if (error == DeclarationError_Parameters) {
        return StringLiteral("too many procedure parameters");
    }
    if (error == DeclarationError_DefaultValue) {
        return StringLiteral("default parameter needs a value");
    }
    if (error == DeclarationError_UsingModifier) {
        return StringLiteral("using parameter modifiers are not supported");
    }
    if (error == DeclarationError_UsingType) {
        return StringLiteral("using parameter needs name: Type");
    }
    if (error == DeclarationError_UsingName) {
        return StringLiteral("using parameter needs a plain name");
    }
    if (error == DeclarationError_ImportQuote) {
        return StringLiteral("Jai #import requires a quoted module or file name");
    }
    if (error == DeclarationError_ImportCharacter) {
        return StringLiteral("#import target contains a character that cannot appear in an include path");
    }
    if (error == DeclarationError_ImportMode) {
        return StringLiteral("unsupported #import mode");
    }
    if (error == DeclarationError_ImportDirSyntax) {
        return StringLiteral("#import, dir requires a quoted path and ';'");
    }
    if (error == DeclarationError_ImportDirPath) {
        return StringLiteral("#import, dir requires a relative directory path");
    }
    if (error == DeclarationError_ImportDirName) {
        return StringLiteral("#import, dir path needs an identifier directory name");
    }
    if (error == DeclarationError_ImportFileSyntax) {
        return StringLiteral("#import, file requires a quoted path and ';'");
    }
    if (error == DeclarationError_ImportFilePath) {
        return StringLiteral("#import, file requires a relative .zi path");
    }
    if (error == DeclarationError_ImportFileName) {
        return StringLiteral("#import, file path needs an identifier filename");
    }
    if (error == DeclarationError_ImportAlias) {
        return StringLiteral("import alias must start with a letter or underscore");
    }
    if (error == DeclarationError_ImportTarget) {
        String value_0 = StringLiteral("Jai #import requires a module identifier or PACKAGE/Module; use #import, file for paths");
        return value_0;
    }
    if (error == DeclarationError_ImportPackage) {
        return StringLiteral("a package import has one '/', as in #import \"PACKAGE/Module\"");
    }
    if (error == DeclarationError_ImportUsing) {
        return StringLiteral("using #import requires a named module alias");
    }
    if (error == DeclarationError_LibraryQuote) {
        return StringLiteral("#system_library requires a quoted library name");
    }
    if (error == DeclarationError_LibraryEnd) {
        return StringLiteral("#system_library declaration must end with ';'");
    }
    if (error == DeclarationError_LibraryCharacter) {
        return StringLiteral("#system_library name contains an invalid character");
    }
    if (error == DeclarationError_UsingKind) {
        return StringLiteral("using modifier must be only, except, or map");
    }
    if (error == DeclarationError_UsingList) {
        return StringLiteral("using modifier requires a parenthesized name list");
    }
    if (error == DeclarationError_UsingEntry) {
        return StringLiteral("using modifier entries must be quoted names");
    }
    if (error == DeclarationError_UsingMap) {
        return StringLiteral("using map entries need \"new\" = \"old\"");
    }
    return StringLiteral("");
}

UsingFilter
compiler_declaration_UsingModifierClause(String source, Slice output, int64_t name_limit)
{
    UsingFilter result = {0};
    int64_t value_0 = (int64_t)(source).length;
    if (value_0 == 0LL || (uint8_t)ZIRAN_INDEX(source.data, source.length, 0) != 44) {
        return result;
    }
    result.present = true;
    int64_t at = compiler_text_SkipSpace(source, 1LL, false);
    String value_1 = source;
    String mode = StringRange(value_1, (int64_t)at, (int64_t)value_1.length);
    String prefix = StringLiteral("");
    if (compiler_source_StartsWord(mode, StringLiteral("only"))) {
        prefix = StringLiteral("O:");
        at = (int64_t)((uint64_t)at + UINT64_C(4));
    } else if (compiler_source_StartsWord(mode, StringLiteral("except"))) {
        prefix = StringLiteral("E:");
        at = (int64_t)((uint64_t)at + UINT64_C(6));
    } else if (compiler_source_StartsWord(mode, StringLiteral("map"))) {
        prefix = StringLiteral("M:");
        at = (int64_t)((uint64_t)at + UINT64_C(3));
    } else {
        result.error = DeclarationError_UsingKind;
        return result;
    }
    at = compiler_text_SkipSpace(source, at, false);
    int64_t value_2 = (int64_t)(source).length;
    if (at >= value_2 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 40) {
        result.error = DeclarationError_UsingList;
        return result;
    }
    at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)), false);
    compiler_declaration_Put(output, &(result.count), prefix);
    int64_t entries = 0LL;
    while (true) {
        int64_t value_3 = (int64_t)(source).length;
        if (!(at < value_3 && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 41)) { break; }
        String value_4 = source;
        QuotedText value_5 = compiler_declaration_UsingQuoted(StringRange(value_4, (int64_t)at, (int64_t)value_4.length), name_limit);
        QuotedText quoted = value_5;
        if (!quoted.valid) {
            result.error = DeclarationError_UsingEntry;
            return result;
        }
        String name = quoted.value;
        at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + (uint64_t)(quoted.end)), false);
        String mapped = StringLiteral("");
        if (StringEqual(prefix, StringLiteral("M:"))) {
            int64_t value_6 = (int64_t)(source).length;
            if (at >= value_6 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 61) {
                result.error = DeclarationError_UsingMap;
                return result;
            }
            at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)), false);
            String value_7 = source;
            QuotedText value_8 = compiler_declaration_UsingQuoted(StringRange(value_7, (int64_t)at, (int64_t)value_7.length), name_limit);
            quoted = value_8;
            if (!quoted.valid) {
                result.error = DeclarationError_UsingMap;
                return result;
            }
            mapped = quoted.value;
            at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + (uint64_t)(quoted.end)), false);
        }
        if (entries > 0LL) {
            compiler_declaration_Put(output, &(result.count), StringLiteral(","));
        }
        compiler_declaration_Put(output, &(result.count), name);
        if (StringEqual(prefix, StringLiteral("M:"))) {
            compiler_declaration_Put(output, &(result.count), StringLiteral("="));
            compiler_declaration_Put(output, &(result.count), mapped);
        }
        entries = (int64_t)((uint64_t)entries + UINT64_C(1));
        int64_t value_9 = (int64_t)(source).length;
        if (at >= value_9 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 44) {
            break;
        }
        at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)), false);
    }
    bool value_10 = entries == 0LL;
    if (!value_10) {
        int64_t value_11 = (int64_t)(source).length;
        value_10 = (at >= value_11);
    }
    if (value_10 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 41) {
        result.error = DeclarationError_UsingList;
        return result;
    }
    int64_t value_12 = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + UINT64_C(1)), false);
    result.next = value_12;
    return result;
}

static QuotedText
compiler_declaration_UsingQuoted(String source, int64_t limit)
{
    int64_t value_0 = (int64_t)(source).length;
    if (value_0 == 0LL || (uint8_t)ZIRAN_INDEX(source.data, source.length, 0) != 34) {
        return (QuotedText){0};
    }
    int64_t at = 1LL;
    while (true) {
        int64_t value_1 = (int64_t)(source).length;
        bool value_2 = at < value_1 && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 34 && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 0;
        if (!value_2) { break; }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    int64_t value_3 = (int64_t)(source).length;
    bool value_4 = at == value_3 || (uint8_t)ZIRAN_INDEX(source.data, source.length, at) != 34 || at == 1LL;
    if (!value_4) {
        int64_t value_5 = (int64_t)((uint64_t)at - UINT64_C(1));
        value_4 = (value_5 >= limit);
    }
    if (value_4) {
        return (QuotedText){0};
    }
    String value_6 = source;
    return (QuotedText){.valid = true, .value = StringRange(value_6, (int64_t)1LL, (int64_t)at), .end = (int64_t)((uint64_t)at + UINT64_C(1))};
}

ExportDirective
compiler_declaration_ProgramExport(String source, int64_t symbol_limit)
{
    ExportDirective result = {0};
    bool value_0 = compiler_source_StartsWord(source, StringLiteral("#program_export"));
    if (!value_0) {
        return result;
    }
    int64_t at = compiler_text_SkipSpace(source, 15LL, true);
    int64_t value_1 = (int64_t)(source).length;
    if (at < value_1 && (uint8_t)ZIRAN_INDEX(source.data, source.length, at) == 34) {
        String value_2 = source;
        QuotedText value_3 = compiler_declaration_Quoted(StringRange(value_2, (int64_t)at, (int64_t)value_2.length), symbol_limit);
        QuotedText quoted = value_3;
        if (!quoted.valid) {
            result.error = DeclarationError_ExportQuote;
            return result;
        }
        result.symbol = quoted.value;
        bool value_4 = compiler_source_IdentifierText(result.symbol, false);
        if (!value_4) {
            result.error = DeclarationError_ExportName;
            return result;
        }
        at = compiler_text_SkipSpace(source, (int64_t)((uint64_t)at + (uint64_t)(quoted.end)), true);
    }
    result.kind = 1;
    int64_t value_5 = (int64_t)(source).length;
    if (at < value_5) {
        result.kind = 2;
    }
    String value_6 = source;
    result.body = StringRange(value_6, (int64_t)at, (int64_t)value_6.length);
    return result;
}

ParameterRewrite
compiler_declaration_RewriteParameters(String source, Slice output, bool strip_defaults, bool strip_using, int64_t name_limit)
{
    ParameterRewrite result = {0};
    int64_t value_0 = compiler_text_SkipSpace(source, 0LL, true);
    int64_t value_1 = (int64_t)(source).length;
    if (value_0 == value_1) {
        return result;
    }
    int64_t at = 0LL;
    while (at >= 0LL) {
        if (result.parameters == 64) {
            result.error = DeclarationError_Parameters;
            return result;
        }
        SourcePart range = compiler_text_NextSourcePart(source, at);
        String value_2 = source;
        String part = compiler_declaration_Trim(StringRange(value_2, (int64_t)range.begin, (int64_t)range.end));
        if (strip_defaults) {
            int64_t assignment = compiler_text_TopLevelAssignment(part);
            if (assignment >= 0LL) {
                int64_t value_3 = compiler_text_SkipSpace(part, (int64_t)((uint64_t)assignment + UINT64_C(1)), true);
                int64_t value_4 = (int64_t)(part).length;
                if (value_3 == value_4) {
                    result.error = DeclarationError_DefaultValue;
                    return result;
                }
                String value_5 = part;
                part = compiler_declaration_Trim(StringRange(value_5, (int64_t)0LL, (int64_t)assignment));
                result.has_defaults = true;
            }
        }
        bool value_6 = strip_using;
        bool value_7 = value_6;
        if (value_7) {
            bool value_8 = compiler_source_StartsWord(part, StringLiteral("using"));
            value_7 = value_8;
        }
        if (value_7) {
            int64_t value_9 = (int64_t)(part).length;
            bool value_10 = value_9 <= 5LL;
            bool value_11 = value_10;
            if (!value_11) {
                bool value_12 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(part.data, part.length, 5));
                value_11 = !value_12;
            }
            if (value_11) {
                result.error = DeclarationError_UsingModifier;
                return result;
            }
            String value_13 = part;
            part = compiler_declaration_Trim(StringRange(value_13, (int64_t)5LL, (int64_t)value_13.length));
            int64_t colon = compiler_declaration_Find(part, StringLiteral(":"));
            if (colon <= 0LL || colon >= name_limit) {
                result.error = DeclarationError_UsingType;
                return result;
            }
            String value_14 = part;
            String value_15 = compiler_declaration_Trim(StringRange(value_14, (int64_t)0LL, (int64_t)colon));
            bool value_16 = compiler_source_IdentifierText(value_15, false);
            if (!value_16) {
                result.error = DeclarationError_UsingName;
                return result;
            }
            result.using_parameters = (uint64_t)((uint64_t)(result.using_parameters) | (uint64_t)(IntegerOp((uint64_t)(1ULL), (uint64_t)((uint64_t)(result.parameters)), 64, 0, 6)));
        }
        if (result.parameters > 0) {
            compiler_declaration_Put(output, &(result.count), StringLiteral(", "));
        }
        compiler_declaration_Put(output, &(result.count), part);
        result.parameters = (int32_t)((uint32_t)(result.parameters) + 1u);
        at = range.next;
    }
    return result;
}

ModuleImport
compiler_declaration_ImportDeclaration(String source, int64_t name_limit, int64_t path_limit)
{
    ModuleImport result = {0};
    int64_t directive = compiler_declaration_Find(source, StringLiteral("#import"));
    if (directive < 0LL) {
        return result;
    }
    String body = source;
    bool value_0 = compiler_source_StartsWord(source, StringLiteral("using"));
    result.using_import = value_0;
    if (result.using_import) {
        String value_1 = source;
        int64_t value_2 = compiler_text_SkipSpace(source, 5LL, true);
        body = StringRange(value_1, (int64_t)value_2, (int64_t)value_1.length);
        int64_t value_3 = (int64_t)(body).length;
        bool value_4 = value_3 == 0LL;
        bool value_5 = value_4;
        if (!value_5) {
            String value_6 = body;
            bool value_7 = compiler_source_IdentifierText(StringRange(value_6, (int64_t)0LL, (int64_t)1LL), false);
            value_5 = !value_7;
        }
        if (value_5) {
            return result;
        }
    }
    result.present = true;
    String value_8 = source;
    QuotedText value_9 = compiler_declaration_Quoted(StringRange(value_8, (int64_t)directive, (int64_t)value_8.length), path_limit);
    QuotedText quoted = value_9;
    if (!quoted.valid) {
        result.error = DeclarationError_ImportQuote;
        return result;
    }
    result.target = quoted.value;
    {
        String value_10 = result.target;
        String loop_view_20 = StringRange(value_10, (int64_t)0, (int64_t)value_10.length);
        int64_t loop_count_20 = (int64_t)(loop_view_20).length;
        int64_t loop_cursor_20 = 0LL;
        while (loop_cursor_20 < loop_count_20) {
            int64_t loop_index_20 = loop_cursor_20;
            uint8_t byte = (uint8_t)ZIRAN_INDEX(loop_view_20.data, loop_view_20.length, loop_index_20);
            if (byte == 34 || byte == 62 || byte < 32) {
                result.error = DeclarationError_ImportCharacter;
                return result;
            }
            loop_cursor_20 = (int64_t)((uint64_t)loop_cursor_20 + UINT64_C(1));
        }
    }
    String value_11 = source;
    int64_t value_12 = compiler_text_SkipSpace(source, (int64_t)((uint64_t)directive + UINT64_C(7)), true);
    String mode = StringRange(value_11, (int64_t)value_12, (int64_t)value_11.length);
    int64_t value_13 = (int64_t)(mode).length;
    if (value_13 > 0LL && (uint8_t)ZIRAN_INDEX(mode.data, mode.length, 0) == 44) {
        String value_14 = mode;
        int64_t value_15 = compiler_text_SkipSpace(mode, 1LL, true);
        mode = StringRange(value_14, (int64_t)value_15, (int64_t)value_14.length);
        int64_t keyword = 0LL;
        int64_t value_16 = (int64_t)(mode).length;
        bool value_17 = value_16 > 3LL;
        if (value_17) {
            String value_18 = mode;
            value_17 = (StringEqual(StringRange(value_18, (int64_t)0LL, (int64_t)3LL), StringLiteral("dir")));
        }
        bool value_19 = value_17;
        bool value_20 = value_19;
        if (value_20) {
            bool value_21 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(mode.data, mode.length, 3));
            value_20 = value_21;
        }
        if (value_20) {
            result.mode = ImportMode_Directory;
            keyword = 3LL;
        } else {
            int64_t value_22 = (int64_t)(mode).length;
            bool value_23 = value_22 > 4LL;
            if (value_23) {
                String value_24 = mode;
                value_23 = (StringEqual(StringRange(value_24, (int64_t)0LL, (int64_t)4LL), StringLiteral("file")));
            }
            bool value_25 = value_23;
            bool value_26 = value_25;
            if (value_26) {
                bool value_27 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(mode.data, mode.length, 4));
                value_26 = value_27;
            }
            if (value_26) {
                result.mode = ImportMode_File;
                keyword = 4LL;
            } else {
                result.error = DeclarationError_ImportMode;
                result.detail = mode;
                return result;
            }
        }
        String value_28 = mode;
        int64_t value_29 = compiler_text_SkipSpace(mode, keyword, true);
        String argument = StringRange(value_28, (int64_t)value_29, (int64_t)value_28.length);
        QuotedText path = compiler_declaration_Quoted(argument, path_limit);
        int64_t value_30 = (int64_t)(argument).length;
        bool value_31 = value_30 == 0LL || (uint8_t)ZIRAN_INDEX(argument.data, argument.length, 0) != 34 || !path.valid;
        bool value_32 = value_31;
        if (!value_32) {
            String value_33 = argument;
            int64_t value_34 = compiler_text_SkipSpace(argument, path.end, true);
            bool value_35 = !StringEqual(StringRange(value_33, (int64_t)value_34, (int64_t)value_33.length), StringLiteral(";"));
            value_32 = value_35;
        }
        if (value_32) {
            result.error = DeclarationError_ImportFileSyntax;
            if (((ImportMode)(result.mode)) == ImportMode_Directory) {
                result.error = DeclarationError_ImportDirSyntax;
            }
            return result;
        }
        String value_36 = compiler_declaration_SymbolBeforeColons(source, name_limit);
        result.name = value_36;
        int64_t value_37 = (int64_t)(result.name).length;
        result.named = value_37 > 0LL;
        result.path = result.target;
        int64_t value_38 = (int64_t)(result.path).length;
        bool valid = value_38 > 0LL && (uint8_t)ZIRAN_INDEX(result.path.data, result.path.length, 0) != 47;
        if (((ImportMode)(result.mode)) == ImportMode_Directory) {
            bool value_39 = valid;
            bool value_40 = value_39;
            if (value_40) {
                int64_t value_41 = compiler_declaration_Find(result.path, StringLiteral("\\"));
                value_40 = (value_41 < 0LL);
            }
            bool value_42 = value_40;
            if (value_42) {
                uint8_t value_43 = (uint8_t)ZIRAN_INDEX(result.path.data, result.path.length, ((int64_t)((uint64_t)((int64_t)(result.path).length) - UINT64_C(1))));
                value_42 = (value_43 != 47);
            }
            valid = value_42;
        } else {
            bool value_44 = valid;
            if (value_44) {
                int64_t value_45 = (int64_t)(result.path).length;
                value_44 = (value_45 >= 4LL);
            }
            bool value_46 = value_44;
            if (value_46) {
                String value_47 = result.path;
                String value_48 = StringRange(value_47, (int64_t)((int64_t)((uint64_t)((int64_t)(result.path).length) - UINT64_C(3))), (int64_t)value_47.length);
                value_46 = (StringEqual(value_48, StringLiteral(".zi")));
            }
            valid = value_46;
        }
        if (!valid) {
            result.error = DeclarationError_ImportFilePath;
            if (((ImportMode)(result.mode)) == ImportMode_Directory) {
                result.error = DeclarationError_ImportDirPath;
            }
            return result;
        }
        String stem = compiler_declaration_Basename(result.path);
        if (((ImportMode)(result.mode)) == ImportMode_File) {
            String value_49 = stem;
            String value_50 = StringRange(value_49, (int64_t)0LL, (int64_t)((int64_t)((uint64_t)((int64_t)(stem).length) - UINT64_C(3))));
            stem = value_50;
        }
        int64_t value_51 = (int64_t)(stem).length;
        bool value_52 = value_51 >= name_limit;
        bool value_53 = value_52;
        if (!value_53) {
            bool value_54 = compiler_source_IdentifierText(stem, false);
            value_53 = !value_54;
        }
        if (value_53) {
            result.error = DeclarationError_ImportFileName;
            if (((ImportMode)(result.mode)) == ImportMode_Directory) {
                result.error = DeclarationError_ImportDirName;
            }
            return result;
        }
        if (!result.named) {
            result.name = stem;
        }
        result.target = stem;
    } else {
        String value_55 = compiler_declaration_SymbolBeforeColons(body, name_limit);
        result.name = value_55;
        int64_t value_56 = (int64_t)(result.name).length;
        result.named = value_56 > 0LL;
        if (!result.named) {
            int64_t slash = compiler_declaration_Find(result.target, StringLiteral("/"));
            if (slash < 0LL) {
                result.name = result.target;
            } else {
                String value_57 = result.target;
                String value_58 = StringRange(value_57, (int64_t)((int64_t)((uint64_t)slash + UINT64_C(1))), (int64_t)value_57.length);
                result.name = value_58;
            }
            int64_t value_59 = (int64_t)(result.name).length;
            if (value_59 >= name_limit) {
                String value_60 = result.name;
                result.name = StringRange(value_60, (int64_t)0LL, (int64_t)((int64_t)((uint64_t)name_limit - UINT64_C(1))));
            }
        }
    }
    bool value_61 = result.named;
    bool value_62 = value_61;
    if (value_62) {
        String value_63 = result.name;
        bool value_64 = compiler_source_IdentifierText(StringRange(value_63, (int64_t)0LL, (int64_t)1LL), false);
        value_62 = !value_64;
    }
    if (value_62) {
        result.error = DeclarationError_ImportAlias;
        return result;
    }
    int64_t slash = compiler_declaration_Find(result.target, StringLiteral("/"));
    if (slash < 0LL) {
        bool value_65 = compiler_source_IdentifierText(result.target, false);
        if (!value_65) {
            result.error = DeclarationError_ImportTarget;
            return result;
        }
    } else {
        String value_66 = result.target;
        String package = StringRange(value_66, (int64_t)0LL, (int64_t)slash);
        String value_67 = result.target;
        String value_68 = StringRange(value_67, (int64_t)((int64_t)((uint64_t)slash + UINT64_C(1))), (int64_t)value_67.length);
        String module = value_68;
        int64_t next = compiler_declaration_Find(module, StringLiteral("/"));
        String first = module;
        if (next >= 0LL) {
            String value_69 = module;
            first = StringRange(value_69, (int64_t)0LL, (int64_t)next);
        }
        bool value_70 = compiler_source_IdentifierText(package, false);
        bool value_71 = !value_70;
        if (!value_71) {
            bool value_72 = compiler_source_IdentifierText(first, false);
            value_71 = !value_72;
        }
        if (value_71) {
            result.error = DeclarationError_ImportTarget;
            return result;
        }
        if (next >= 0LL) {
            result.error = DeclarationError_ImportPackage;
            return result;
        }
    }
    if (result.using_import && !result.named) {
        result.error = DeclarationError_ImportUsing;
    }
    return result;
}

LibraryDeclaration
compiler_declaration_SystemLibrary(String source, int64_t name_limit, int64_t path_limit)
{
    LibraryDeclaration result = {0};
    String value_0 = compiler_declaration_SymbolBeforeColons(source, name_limit);
    result.name = value_0;
    int64_t value_1 = (int64_t)(result.name).length;
    if (value_1 == 0LL) {
        return result;
    }
    String value_2 = source;
    String value_3 = source;
    int64_t value_4 = (int64_t)((uint64_t)(compiler_declaration_Find(source, StringLiteral("::"))) + UINT64_C(2));
    int64_t value_5 = compiler_text_SkipSpace(value_3, value_4, true);
    String declaration = StringRange(value_2, (int64_t)value_5, (int64_t)value_2.length);
    bool value_6 = compiler_source_StartsWord(declaration, StringLiteral("#system_library"));
    if (!value_6) {
        return result;
    }
    result.present = true;
    String value_7 = declaration;
    int64_t value_8 = compiler_text_SkipSpace(declaration, 15LL, true);
    String argument = StringRange(value_7, (int64_t)value_8, (int64_t)value_7.length);
    QuotedText quoted = compiler_declaration_Quoted(argument, path_limit);
    int64_t value_9 = (int64_t)(argument).length;
    bool value_10 = value_9 == 0LL || (uint8_t)ZIRAN_INDEX(argument.data, argument.length, 0) != 34 || !quoted.valid;
    if (!value_10) {
        int64_t value_11 = (int64_t)(quoted.value).length;
        value_10 = (value_11 == 0LL);
    }
    if (value_10) {
        result.error = DeclarationError_LibraryQuote;
        return result;
    }
    result.target = quoted.value;
    String value_12 = argument;
    int64_t value_13 = compiler_text_SkipSpace(argument, quoted.end, true);
    bool value_14 = !StringEqual(StringRange(value_12, (int64_t)value_13, (int64_t)value_12.length), StringLiteral(";"));
    if (value_14) {
        result.error = DeclarationError_LibraryEnd;
        return result;
    }
    {
        String value_15 = result.target;
        String loop_view_21 = StringRange(value_15, (int64_t)0, (int64_t)value_15.length);
        int64_t loop_count_21 = (int64_t)(loop_view_21).length;
        int64_t loop_cursor_21 = 0LL;
        while (loop_cursor_21 < loop_count_21) {
            int64_t loop_index_21 = loop_cursor_21;
            uint8_t byte = (uint8_t)ZIRAN_INDEX(loop_view_21.data, loop_view_21.length, loop_index_21);
            if (byte < 32 || byte == 34 || byte == 92) {
                result.error = DeclarationError_LibraryCharacter;
                return result;
            }
            loop_cursor_21 = (int64_t)((uint64_t)loop_cursor_21 + UINT64_C(1));
        }
    }
    return result;
}

MethodSymbol
compiler_declaration_ForeignMethod(String source, int64_t receiver_limit, int64_t method_limit, bool python)
{
    MethodSymbol result = {0};
    int64_t dot = compiler_declaration_Find(source, StringLiteral("."));
    if (dot <= 0LL) {
        return result;
    }
    String value_0 = source;
    result.receiver = StringRange(value_0, (int64_t)0LL, (int64_t)dot);
    String value_1 = source;
    result.method = StringRange(value_1, (int64_t)((int64_t)((uint64_t)dot + UINT64_C(1))), (int64_t)value_1.length);
    if ((uint8_t)ZIRAN_INDEX(source.data, source.length, 0) == 40) {
        int64_t value_2 = (int64_t)(result.receiver).length;
        bool value_3 = value_2 < 3LL;
        if (!value_3) {
            uint8_t value_4 = (uint8_t)ZIRAN_INDEX(result.receiver.data, result.receiver.length, ((int64_t)((uint64_t)((int64_t)(result.receiver).length) - UINT64_C(1))));
            value_3 = (value_4 != 41);
        }
        if (value_3) {
            return result;
        }
        String value_5 = result.receiver;
        String value_6 = StringRange(value_5, (int64_t)1LL, (int64_t)((int64_t)((uint64_t)((int64_t)(result.receiver).length) - UINT64_C(1))));
        result.receiver = value_6;
    } else if (python) {
        return result;
    }
    int64_t value_7 = (int64_t)(result.receiver).length;
    bool value_8 = value_7 >= receiver_limit;
    if (!value_8) {
        int64_t value_9 = (int64_t)(result.method).length;
        value_8 = (value_9 >= method_limit);
    }
    if (value_8) {
        return result;
    }
    String name = result.receiver;
    int64_t value_10 = (int64_t)(name).length;
    if (value_10 > 0LL && (uint8_t)ZIRAN_INDEX(name.data, name.length, 0) == 42) {
        if (python) {
            return result;
        }
        String value_11 = name;
        name = StringRange(value_11, (int64_t)1LL, (int64_t)value_11.length);
    }
    bool value_12 = compiler_source_IdentifierText(name, false);
    bool value_13 = value_12;
    if (value_13) {
        bool value_14 = compiler_source_IdentifierText(result.method, false);
        value_13 = value_14;
    }
    result.valid = value_13;
    return result;
}

bool
compiler_declaration_PythonAttribute(String source, int64_t name_limit)
{
    int64_t at = 0LL;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at <= value_0)) { break; }
        String value_1 = source;
        int64_t value_2 = compiler_declaration_Find(StringRange(value_1, (int64_t)at, (int64_t)value_1.length), StringLiteral("."));
        int64_t end = value_2;
        if (end < 0LL) {
            end = (int64_t)((uint64_t)((int64_t)(source).length) - (uint64_t)at);
        }
        String value_3 = source;
        String part = StringRange(value_3, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)end)));
        int64_t value_4 = (int64_t)(part).length;
        bool value_5 = value_4 >= name_limit;
        bool value_6 = value_5;
        if (!value_6) {
            bool value_7 = compiler_source_IdentifierText(part, false);
            value_6 = !value_7;
        }
        if (value_6) {
            return false;
        }
        at = (int64_t)((uint64_t)at + (uint64_t)end);
        int64_t value_8 = (int64_t)(source).length;
        if (at == value_8) {
            return true;
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return false;
}
